### ISSUE TITLE
Provide flatpak for signal-desktop-beta

### ISSUE THREAD

**Issue by fmikker** [flathub/org.signal.Signal#10]
Hi, 

I was just in touch with OWS support regarding joining the beta program, but as OWS only provides *.deb-packages and I'm running Fedora 27 I can't install the beta via the proposed way they describe.

But since I'm running the stable version via Flatpak I would like to propose that we create a flatpak installation method for the beta as well.

Any comments on this?

**Comment by Barthalion** [comment]
Flathub is supposed to host only stable releases for now. It may change in the future, but more likely only for manifests maintained by upstream.

**Comment by nedrichards** [comment]
To add to this, if OWS would like to host their own flatpak repo with beta releases - then that sounds awesome, but as @Barthalion says, that's 'not for flathub'.

**Comment by fmikker** [comment]
I'm aware that Flathub should provide stable releases, but is it possible to create a installation package of the beta, based on the beta deb-packages  and maintain it outside of flathub just for testing purposes would be beneficial for OWS to get some more eyes on the software and find bugs.

What I'm proposing is creating a community-only beta flatpak package and I thought if someone in this project would like to do so as well.

I've already talked with OWS support and at this time they have no plans providing any other packages besides .deb for the foreseeable future.

I'll see what I can do by my self, and while at it - learning flatpak a bit better.

**Comment by nedrichards** [comment]
Oh sure - feel free to fork the Signal repo here. In the first instance you should just need to change the URLs and add the new size and sha256sum information. Then run something like `flatpak-builder --force-clean  --require-changes --repo=repo app org.signal.Desktop.json ` to build `flatpak --user remote-add --no-gpg-verify signal-repo repo ` and then `flatpak --user install signal-repo org.signal.Desktop`. For more on publishing a repo there are some [docs here](http://docs.flatpak.org/en/latest/distributing-applications.html).

Feel free to ask for help on IRC as well if you need it. #flatpak on freenode.

**Comment by bermeitinger-b** [comment]
As far as I know, OWS does not provide deb files for the beta version that could be added to the json file. You need to build the deb file on your own and reference it not via https but file:// protocol ([like here](https://github.com/bermeitinger-b/org.signal.Signal/blob/beta/org.signal.Signal.json))
But if you build it locally, the build process does not produce a file with the same SHA256 sum each run, you need to change it every time.
You can do this for using the beta with flatpak but currently not via the current flathub build script.

**Comment by nedrichards** [comment]
Ah right - different technique then! You'll need to build from source. You can use the handy new flatpak-npm tool https://github.com/flatpak/flatpak-builder-tools although note - you'll have to run npm5 on your checked out [Signal Desktop](https://github.com/WhisperSystems/Signal-Desktop) first in order to create the package-lock.json file.  (or you can add yarn.lock support to the tool!) but that should give you a bunch of stuff to add to the flatpak manifest.

It won't be super easy, because this is a 'pioneering' area for flatpak and there aren't a lot of other examples to copy. But it'd be totally possible and very worthwhile.

**Comment by fmikker** [comment]
@bermeitinger-b they do provide beta packages for Signal Desktop, and I have signed up for it. But I haven't looked at trying to make something out of it yet.
You can find more info here on how to join the beta program: https://support.signal.org/hc/en-us/articles/115000269532-How-do-I-join-Signal-s-beta-

Repo config Linux 64-bit distributions supporting APT, like Ubuntu or Debian:
```
$ curl -s https://updates.signal.org/desktop/apt/keys.asc | sudo apt-key add - 
$ echo "deb [arch=amd64] https://updates.signal.org/desktop/apt xenial main" | sudo tee -a /etc/apt/sources.list.d/signal-xenial.list 
$ sudo apt update && sudo apt install signal-desktop-beta
```

**Comment by bermeitinger-b** [comment]
On their page, they write that you should send an email if you want beta access. Publically releasing this version of flathub would circumvent this restriction. Although judging from your snippet, the registration step is not required, but still, we need a reliable hotlink to the beta's deb file.
