### ISSUE TITLE
Update to 1.29.4

### ISSUE THREAD

**Issue by prometoys** [flathub/org.signal.Signal#109]
Hi,

currently it's not possible to send messages with signal. The desktop app demands an update. Win,Mac and deb are at 1.29.4

**Comment by bermeitinger-b** [comment]
I can't reproduce. Are you sure you are on version 1.29.4?

**Comment by prometoys** [comment]
No, I'm on Signal 1.29.3 on Fedora via Flathub. But I guess my bug report overlapped with the new update. I will try tomorrow again. I don't have access to the fedora pc atm. 

Btw.: Thanks for your package.

**Comment by prometoys** [comment]
Sorry, forget to report here. After the update to 1.29.4 I had still the problem. After deinstall the package and reinstall it, everything worked as expected. Thanks.
