### ISSUE TITLE
Can't send messages; fixed in upstream v1.29.6

### ISSUE THREAD

**Issue by swick** [flathub/org.signal.Signal#110]
https://github.com/signalapp/Signal-Desktop/issues/3879#issuecomment-575513573

**Comment by bermeitinger-b** [comment]
Update to v1.29.6 is in #111

**Comment by swick** [comment]
Great, thanks!

**Comment by hoergen** [comment]
The Linux repositories for the desktop still throwing an error and you only get buggy version 1.29.3
