### ISSUE TITLE
Filesystem sandbox does not work

### ISSUE THREAD

**Issue by sigint2** [flathub/org.signal.Signal#114]
The filesystem sandbox does not work. Tested on the latest version of Signal flatpak, 2 separate Fedora 30/31 boxes.

**Problem:**

/var/lib/flatpak/app/org.signal.Signal/current/active/metadata contains the following type:
...
filesystems=home
...

For the sandbox to work (per the flatpak man) this must be filesystem=home, not the plural "filesystems". Oddly, https://github.com/flathub/org.signal.Signal/blob/25b4df39faf4b9281a966cb190ea345c29d8dd97/org.signal.Signal.json has the correct spelling of filesystem. 

Where is this getting altered?

**Comment by TingPing** [comment]
The application has no control over that, its a file generated by `flatpak-builder`. It is also correct: `man flatpak-metadata`.
