### ISSUE TITLE
No tray icon on Fedora/Gnome

### ISSUE THREAD

**Issue by ruffson** [flathub/org.signal.Signal#116]
Hi there,
sadly there is no tray icon on Fedora31 with Gnome 3.34.3 and Signal version 1.31.0.
I have enabled the extensions `KStatusNotifierItem/AppIndicator` (aka `ubuntu/gnome-shell-extension-appindicator`) and `TopIcons Plus`.
Is there a way to enable is? Do I have to install yet another gnome extension to make it work? Any help is appreciated!s

**Comment by bermeitinger-b** [comment]
You have to run it with `flatpak run org.signal.Signal --use-tray-icon`.

**Comment by ruffson** [comment]
> You have to run it with `flatpak run org.signal.Signal --use-tray-icon`.

Thank you! Is there a way to make this the defaul so I can call it like that when I open the .desktop file via Gnome?

**Comment by mlaradji** [comment]
@ruffson Edit the `.desktop` file and change:
```
Exec=/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=signal --file-forwarding org.signal.Signal @@u %U @@
```
to
```
Exec=/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=signal --file-forwarding org.signal.Signal @@u %U @@ --use-tray-icon
```

Note that launching the shortcut from the start menu (on KDE) does not reflect the change immediately, and I had to launch the desktop shortcut from Dolphin first (not sure why, but probably due to some sort of caching).

**Comment by ruffson** [comment]
Tha

> @ruffson Edit the `.desktop` (for me it's in `/var/lib/flatpak/app/org.signal.Signal/current/active/export/share/applications/org.signal.Signal.desktop`) file and change:
> 
> ```
> Exec=/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=signal --file-forwarding org.signal.Signal @@u %U @@
> ```
> 
> to
> 
> ```
> Exec=/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=signal --file-forwarding org.signal.Signal @@u %U @@ --use-tray-icon
> ```
> 
> You can also add the flag `--start-in-tray` like:
> 
> ```
> Exec=/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=signal --file-forwarding org.signal.Signal @@u %U @@ --use-tray-icon --start-in-tray
> ```
> 
> Note that launching the shortcut from the start menu (on KDE) does not reflect the change immediately, and I had to launch the desktop shortcut from Dolphin first (not sure why, but probably due to some sort of caching).

Thank you!

**Comment by MaCroX95** [comment]
I don't see tray icon issue with --use-tray-icon option. It works on my deb-installed beta package but not on the flatpak one.

**Comment by cachandlerdev** [comment]
Unfortunately, the issue with this fix is that it has to be reapplied every time the app updates. Are there any plans to make this default behavior in the future?

**Comment by awkto** [comment]
On the latest flatpak, I get this error when trying to add the '--use-tray-icon' option

`error: Unknown option --use-tray-icon`
