### ISSUE TITLE
Signal –start-in-tray option now prevents launch

### ISSUE THREAD

**Issue by barthalion** [flathub/org.signal.Signal#121]
> Including the --start-in-tray option now prevents Signal from launching. This is fairly recent breakage. I’ve been running this for over a year, but I noticed that Signal was no longer launching at boot.
> After some experimentation, I can confirm that including the --start-in-tray option hangs launch.
> Running KDE Neon version 5.18.2 (based on the current Ubuntu LTS 18.04)

https://discourse.flathub.org/t/signal-start-in-tray-option-now-prevents-launch/237

**Comment by bermeitinger-b** [comment]
This might have to do something with the change to ElectronBaseApp and using zygote-wrapper for sandboxing.

**Comment by ravvle** [comment]
This is fixed upstream: https://github.com/signalapp/Signal-Desktop/releases/tag/v1.33.3

Updating should fix it, I made a pull request: https://github.com/flathub/org.signal.Signal/pull/131

**Comment by bermeitinger-b** [comment]
Is it fixed?
