### ISSUE TITLE
Tray icon not shown anymore

### ISSUE THREAD

**Issue by altruizine** [flathub/org.signal.Signal#127]
I'm running Signal with --use-tray-icon as per #116. This used to show the tray icon, but doesn't do this any longer, likely due to a recent update.

Running Signal 1.32.3 with flatpak 1.4.3 on openSUSE Leap 15.1 with KDE Plasma 5.12.8.

**Comment by Cerberus0** [comment]
This is likely an upstream issue: https://github.com/signalapp/Signal-Desktop/issues/4132

**Comment by ravvle** [comment]
This is fixed upstream: https://github.com/signalapp/Signal-Desktop/releases/tag/v1.33.3

Updating should fix it, I made a pull request: #131

**Comment by Erick555** [comment]
This shold be fixed by https://github.com/flathub/org.signal.Signal/commit/ff3a5942f97a0eb7b96043c0add9092e4b970bf7

**Comment by altruizine** [comment]
I can confirm that the issue appears to be resolved in org.signal.Signal 1.34.1. Thanks!
