### ISSUE TITLE
bwrap: Can't bind mount /oldroot/home/... on /newroot/usr: No such file or directory

### ISSUE THREAD

**Issue by commonist** [flathub/org.signal.Signal#129]
Installation steps to reproduce on alpine linux:

$ sudo apk add flatpak
$ flatpak --user remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrep
$ flatpak install flathub org.signal.Signal
Looking for matches…
Required runtime for org.signal.Signal/x86_64/stable (runtime/org.freedesktop.Platform/x86_64/19.08) found in remote flathub
Do you want to install it? [Y/n]:

org.signal.Signal permissions:
    ipc      network      pulseaudio      x11      dri      file access [1]     dbus access [2]

    [1] home
    [2] org.freedesktop.Notifications, org.kde.StatusNotifierWatcher

        ID                                              Arch              Branch            Remote             Download
 1. [✓] org.freedesktop.Platform                        x86_64            19.08             flathub              224.2 MB / 238.2 MB
 2. [✓] org.freedesktop.Platform.GL.default             x86_64            19.08             flathub               94.9 MB / 94.9 MB
        ID                                              Arch              Branch            Remote             Download
 1. [✓] org.freedesktop.Platform                        x86_64            19.08             flathub            224.2 MB / 238.2 MB
 2. [✓] org.freedesktop.Platform.GL.default             x86_64            19.08             flathub             94.9 MB / 94.9 MB
        ID                                              Arch              Branch            Remote             Download
 1. [✓] org.freedesktop.Platform                        x86_64            19.08             flathub            224.2 MB / 238.2 MB
 2. [✓] org.freedesktop.Platform.GL.default             x86_64            19.08             flathub             94.9 MB / 94.9 MB
 3. [✓] org.freedesktop.Platform.Locale                 x86_64            19.08             flathub             22.9 MB / 318.2 MB
 4. [✓] org.freedesktop.Platform.VAAPI.Intel            x86_64            19.08             flathub              8.7 MB / 8.7 MB
 5. [✗] org.freedesktop.Platform.openh264               x86_64            2.0               flathub            918.1 kB / 916.8 kB
 6. [✓] org.signal.Signal                               x86_64            stable            flathub            135.1 MB / 135.1 MB

Warning: While trying to apply extra data: apply_extra script failed, exit status 256
Installation complete.

$ signal
bwrap: Can't bind mount /oldroot/home/.../.local/share/flatpak/runtime/org.freedesktop.Platform/x86_64/19.08/3df64a7c249c10d57f920728e03f6e749491f5ab9ecc2d5e8ecdb0fc0a5d92c1/files on /newroot/usr: No such file or directory
error: ldconfig failed, exit status 256

**Comment by makoto1984** [comment]
You will resolve it by upgrading musl to edge. Currently, from musl-1.1.24-r2 to musl-1.1.24-r6.
This problem occurs everytime when bwrap is invoked. You may test it by
```
bwrap --bind / / true
```
As you know, flatpak is based on bwrap. So any flatpak app won't run.
I think the bug is located in some musl functions called by bwrap.

**Comment by commonist** [comment]
Thank you very much. At least I know - finally - what the problem is. :-)
