### ISSUE TITLE
Feature request: Signal Desktop Beta

### ISSUE THREAD

**Issue by LoveIsGrief** [flathub/org.signal.Signal#142]
Signal provides a beta version of this package. It would great if it were on flathub too. Then flatpak users could also get access to beta features and report bugs to be fixed before they hit the main branch.

**Comment by LoveIsGrief** [comment]
I found that development releases can be defined in the appdata.xml [as per spec](https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-releases). I just can't figure out how to define the build steps for different releases. The json https://github.com/flathub/org.signal.Signal/blob/master/org.signal.Signal.json targets only one version and I don't know how make it work like a function that takes a `.deb` as a param...

**Comment by LoveIsGrief** [comment]
Closing in favor of https://github.com/flathub/flathub/pull/1798

**Comment by akvadrako** [comment]
Seems the beta flatpak was never accepted. It does seem like it would make more sense as a branch.

According to https://github.com/flathub/flathub/wiki/App-Maintenance the beta version should be in a "beta" branch of this repo.
