### ISSUE TITLE
Pipewire - unability to choose microphone and audio out access for calls

### ISSUE THREAD

**Issue by fourstepper** [flathub/org.signal.Signal#160]
```
$ pipewire --version
pipewire
Compiled with libpipewire 0.3.15
Linked with libpipewire 0.3.15
```

Running pipewire with the Signal Flatpak causes inability to select input and output devices for sound to work on video calls - please see attached screenshot.

![image](https://user-images.githubusercontent.com/49439044/98862069-93363700-2466-11eb-9885-b353ed81a765.png)

**Comment by kaimast** [comment]
Can you upgrade to a newer version of pipewire? I cannot reproduce this on my setup.

**Comment by genodeftest** [comment]
I cannot reproduce the issue either. Pipewire has seen heavy development in the last 1.5 years so the issue may have been fixed on their side a long time ago. I suggest closing this issue.

**Comment by fourstepper** [comment]
I think this might have been an error on my side, but it's really hard to say this retrospectively. I will close this issue now, thank you for the bump
