### ISSUE TITLE
feature request: Startup Application in extension.

### ISSUE THREAD

**Issue by daddydaycare** [flathub/org.signal.Signal#162]
Use signal on android, windows, ios, land several linux distros.  
It really would excel is it could be a startup app and run in background .
Not sure if I am just not noticing how to do that, or if this has been overlooked. Seems like a basic feature.

Cheers!

**Comment by bermeitinger-b** [comment]
This seems like a task for your desktop/window manager. There are too many different combinations to cover everything, so a manual setup makes most sense.

Also, as long as upstream doesn't add this, I see no point do divert.

**Comment by daddydaycare** [comment]
Upstream?  Can this be redirected?  As it really is something long term is in the best interest of this project.  You can have it as a startup app, but signal does not natively have the option to run in background, it has to be open.  Unlike skype or other services that singal is to replace, and the other numerous alts on market now. To have it start open instead of in the  background or as an extension, is less than ideal.  Love it on android, ios, but on desktop this has not been addressed.  Be great to make this know in proper channel.  Thanks

**Comment by bermeitinger-b** [comment]
This is a community flatpak repo. For the official version go to https://github.com/signalapp/Signal-Desktop

What stops you from adding it manually to your startup entries?
