### ISSUE TITLE
Signal says it's disconnected even though the laptop has internet

### ISSUE THREAD

**Issue by ThracianKnight1907** [flathub/org.signal.Signal#169]
![Captură de ecran de la 2021-01-15 21-41-16](https://user-images.githubusercontent.com/64692701/104771131-74139880-577a-11eb-9dae-129e8c30823a.png)

Essentially the title. I'm not sure why this is happening, as I'm using the Internet right now. Checked with flatseal and signal has network access.

I'm currently running the latest Signal from flathub (1.39.5) on Fedora 33.

**Comment by bermeitinger-b** [comment]
It's down for the moment https://twitter.com/signalapp/status/1350118809860886528

**Comment by ThracianKnight1907** [comment]
Ok, I didn't know this. No such message appears on Android so I thought it's a desktop issue.

**Comment by al12gamer** [comment]
Possibly related new issue in https://github.com/flathub/org.signal.Signal/issues/457
