### ISSUE TITLE
Missing ibus support

### ISSUE THREAD

**Issue by SISheogorath** [flathub/org.signal.Signal#17]
Right now signal doesn't support any ibus input, which is needed, when you talk with people who don't use non-western languages.

It may comes from the electron base, at the ibus support is also missing on Slack.

Would be nice to solve the problem.

**Comment by nedrichards** [comment]
@SISheogorath which version of ibus do you have installed?

> ibus version

Needs to show [1.5.17 or later](https://github.com/flatpak/flatpak/issues/675). I haven't tested this myself

**Comment by SISheogorath** [comment]
I have 1.5.17 installed. I'm on latest update state on Fedora.

**Comment by nedrichards** [comment]
Hrm, does the ibus test work ok for you?

https://github.com/ibus/ibus/blob/master/test/org.test.IBus.json

> flatpak-builder --force-clean app org.test.IBus.json
> flatpak-builder --run --nofilesystem=host app org.test.IBus.json zenity --entry

As you say, I think it's very likely that this is an Electron thing - I just want to make sure that it's not more widespread.

**Comment by SISheogorath** [comment]
In the ibus test it works. Even when the needed fonts are missing inthe frontend:

![image](https://user-images.githubusercontent.com/8719867/36797853-50ea72e8-1ca9-11e8-95cc-57df4982f3f7.png)

```
flatpak-builder --run --nofilesystem=host ibus-test org.test.IBus.json zenity --entry

** (zenity:2): WARNING **: Couldn't connect to accessibility bus: Failed to connect to socket /tmp/dbus-MDlzxEZ4o9: Connection refused
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
谢谢你
```

**Comment by SISheogorath** [comment]
Just tested the workaround mentioned in the https://github.com/flatpak/flatpak/issues/1671:

`flatpak run --env=GTK_IM_MODULE=xim org.signal.Signal` and as it turns out, this results in a freeze of the entire application when starting to type a word using ibus. So still quite imperfect.

**Comment by SISheogorath** [comment]
Fixed with latest runtime :) :tada:
