### ISSUE TITLE
Flatpak version can't save files to home

### ISSUE THREAD

**Issue by ceisserer** [flathub/org.signal.Signal#181]
When trying to save files using the linux desktop app installed via signal, I can only save to an "empty" home directory.
My guess is due to flatpak the signal app runs in some kind of sandbox, which provides the signal app with some kind of "fake" home directory - which might be great for security, but actually is painful if you really would like to save files to your real home directory ;)

**Comment by bermeitinger-b** [comment]
We discussed this here heavily and came to the conclusion that opening all available portals sufficient. For example, if you put the files in ~/Downloads or ~/Videos it'll work.

You can open your home directory with the command
`flatpak override --filesystem=home org.sign.Signal`

**Comment by ceisserer** [comment]
I executed the command you suggested, however it only worked as root (otherwise I got permission denied) - and still, I can't access my home directory - however Downloads / Desktop work as expected.

This is a workarround I can live with - however it still seems like a hack. Is the "average user" really expected to cope with stuff like this? I am using several other flatpak applications (netbeans, IntelliJ) which have no issue accessing the whole filesystem as if they were installed nativly.

**Comment by bermeitinger-b** [comment]
Those other applications have full access to the host system. This is something that we restricted a while back because it defeats the sandbox promise.

Instead of "home", you can also add "host" to give full access.

**Comment by Buggem** [comment]
> We discussed this here heavily and came to the conclusion that opening all available portals sufficient. For example, if you put the files in ~/Downloads or ~/Videos it'll work.
> 
> You can open your home directory with the command `flatpak override --filesystem=home org.signal.Signal`

Why would `home` dirs be blocked by default? Config files are stored there, whereas it wouldn't make sense to allow the place where personal files are stored (`~/Documents`).
If anything, reverse your approach and make it that Documents, Videos, Music etc. can't be accessed without user permission.

Your current approach makes no sense.

**Comment by Buggem** [comment]
Take Pingus (`org.seul.Pingus`) for example. It stores its config in `~/.{app name}` (`~/.pingus` in this case), like many other programs do. Why is it sandboxed from accessing that folder, it breaks the game and makes it impossible to save!

**Comment by faveoled** [comment]
> Take Pingus (`org.seul.Pingus`) for example. It stores its config in `~/.{app name}` (`~/.pingus` in this case), like many other programs do. Why is it sandboxed from accessing that folder, it breaks the game and makes it impossible to save!

It's a packaging bug. The flatpak manifest should've provided a config similar to this:
https://github.com/flathub/org.freeciv.gtk4/blob/54eeedd53e7f3f08ae70d7a77e6e279237c6d5fd/org.freeciv.gtk4.yml#L13
