### ISSUE TITLE
File picker does not list files/fodlers in home dir

### ISSUE THREAD

**Issue by lifebarier** [flathub/org.signal.Signal#182]
https://github.com/signalapp/Signal-Desktop/issues/5151

Also - can't drag files into message window if they are in home dir or in dir that is not listed in home dir (eg dragging file from /home/username/customFolder/photo.jpeg)

**Comment by hfiguiere** [comment]
The flatpak doesn't have access to the home directory. Just to a more restricted set. Include "documents", "desktop", "pictures" and "download"

**Comment by lifebarier** [comment]
That is laughably bad. Who designed it this way?
Any workarounds?

**Comment by bermeitinger-b** [comment]
You can use
`flatpak override --filesystem=home org.signal.Signal`
