### ISSUE TITLE
cannot save files on desktop app

### ISSUE THREAD

**Issue by ilippert** [flathub/org.signal.Signal#183]
- [x] I have searched open and closed issues for duplicates

---

### Steps to Reproduce

1.  send a file as a message to yourself
2.  save file as null.txt with your desktop app

Actual Result:

null.txt in desired directory is not present, even though in the Nautilus/file manager that signal uses, the file is shown.
The file's absence is confirmed by shell.

null.txt in desired directory is present.

### Platform Info

Signal Version:

v1.40.1

Operating System:

Linux, Fedora 33

Linked Device Version: 5.6.4

https://debuglogs.org/eb40c8d3416df341525e55c9ae7a1eab19d6cd58b4dba928e46ee4184d22426d

**Comment by hiqua** [comment]
Might be related: https://github.com/flathub/org.signal.Signal/issues/181

**Comment by ilippert** [comment]
Indeed, https://github.com/flathub/org.signal.Signal/issues/181#issuecomment-808864313 explains the issue.
