### ISSUE TITLE
Entire folder missing in home directory

### ISSUE THREAD

**Issue by kdwk** [flathub/org.signal.Signal#185]
**Bug Description**

I host a Nextcloud instance for my cloud storage, and sync that folder to a folder called 'Nextcloud-Kdwk' under my home folder using the official Nextcloud desktop client. For some reason, Signal cannot access or even show the existence of that folder in file chooser, and files cannot be drag and dropped or copied and pasted from Nextcloud-Kdwk to Signal. Everything else in the home folder displays correctly, just not the Nextcloud-Kdwk folder.
Steps to Reproduce

1.     Sync a Nextcloud folder to a directory in your home folder using the official Nextcloud desktop sync client
2.     Try to import the file to Signal
3.     Import a file from any other place

**Actual Result:**

Cannot import file from Nextcloud folder to Signal

**Expected Result:**

File imported from Nextcloud folder to Signal

**Screencast**

https://user-images.githubusercontent.com/39268094/115698723-844d9c00-a397-11eb-8b4d-e0fb96b5f1d3.mp4

**Platform Info**

Signal Version:
5.0.0 (Flatpak from Flathub)

Operating System:
Fedora 34 (Gnome 40, Wayland)

Linked Device Version:

iOS 14.4.2

I opened an issue in Signalapp but was directed to open an issue here instead because it is a Flatpak problem (deb users don't experience this)

**Comment by bermeitinger-b** [comment]
It's not a bug, it's a feature (See #153)

Use `flatpak override --filesystem=host org.signal.Signal` to allow a random third-party program you downloaded from the internet full access to your system.

Or you use the fancy [Flatseal](https://flathub.org/apps/details/com.github.tchx84.Flatseal) to give it full-access permission.
