### ISSUE TITLE
home directory exposed

### ISSUE THREAD

**Issue by muelli** [flathub/org.signal.Signal#20]
Is there a reason why the entire home directory needs to be readable, let alone writeable?
https://github.com/flathub/org.signal.Signal/blob/2d2fed87ce75a861c65c7d1ade61b51009845a3b/org.signal.Signal.json#L18

**Comment by TingPing** [comment]
I would imagine because the app supports uploading and downloading media?

**Comment by muelli** [comment]
But that's what we have portals for, no?  So that the app does not steal all your emails but only the files you actively select.

**Comment by TingPing** [comment]
Yes but the application has to use the portals and it will probably be best case another year before Electron starts using the portals (somebody has to do that work) *and* Signal gets that update.

**Comment by r-cheologist** [comment]
Is that access revocable on the CLI? I figured out that I can add '/tmp' like so:

    flatpak run  --filesystem=/tmp org.signal.Signal

but can I revoke the `$HOME` access baked into the flatpak?

**Comment by r-cheologist** [comment]
flatpak run  --filesystem=/tmp --nofilesystem=$HOME org.signal.Signal

Appears to not work (nor does the explicit expansion of `$HOME`).

**Comment by muelli** [comment]
Try something like
`flatpak --user override org.signal.Signal --nofilesystem=home`

It should show up in `~/.local/share/flatpak/overrides`

**Comment by genodeftest** [comment]
Another reason why electron is a bad choice…

See also: electron/electron#2911

**Comment by vmedea** [comment]
> Try something like
> flatpak --user override org.signal.Signal --nofilesystem=home

> flatpak --user override org.signal.Signal --nofilesystem=home --filesystem=/tmp
> is even better.

wow thank youu

i'm happy that this is possible: i really didn't want to give the application access to my home directory, for it not to be able to get to my files in case of a privilege escalation, that's *the* reason i was interested in using flatpak for it

**Comment by pabl0** [comment]
I use the following override:

```
[Context]
filesystems=xdg-download;!home;
```

I think xdg-downloads would be a reasonable default for saving attachments from Signal. However, I don't what would be the standard folder for uploads/sharing.

**Comment by genodeftest** [comment]
I think the real solution would be to get electron fixed to support being sandboxed. See electron/electron#2911 and electron/electron#19159 for getting the filesystem portal work. If you can help, you might help there. After that has been fixed, Signal can be taken the permissions to access user's home directory.

PS: I still think this is a security-critical issue.

**Comment by bermeitinger-b** [comment]
Added by #154
