### ISSUE TITLE
The option to minimize to system tray of start minimized to tray is not present in version 5.8.0

### ISSUE THREAD

**Issue by Altonss** [flathub/org.signal.Signal#206]
Here what it should look like, according to a post in the signal community forum.
![image](https://user-images.githubusercontent.com/66519591/125194447-a5fd4780-e251-11eb-967d-50d9acb24134.png)
But on my version installled from flathub, this 2 new options are not present.

**Comment by kaimast** [comment]
I can confirm this... 

`flatpak run org.signal.Signal --start-in-tray` still works as expected.

**Comment by bermeitinger-b** [comment]
#283 intoduces two environment variables to use tray and start in tray.
