### ISSUE TITLE
Signal Desktop Freezes

### ISSUE THREAD

**Issue by marcello42** [flathub/org.signal.Signal#237]
The Desktop apps freezes around 10 times per hour for a couple of minutes.
Killsig does not work..

2 different freezes:

1: Display does not show when switching workspaces the app is fully transparent for 2-3 minutes
2: Display shows up, but you cannot click anywhere

--> Chatpartners report that the messages are not going through during this period (only one instead of 2 checkmarks)

Running latest flatpak
x-org
WM: LG3D running Qtile 
OS: Arch
compositor: picom

**Comment by bermeitinger-b** [comment]
You need to give logs. And try without flatpak from the AUR.

**Comment by marcello42** [comment]
where can I find the logs?
The AUR is not an official repo thus not what I prefer.

**Comment by bermeitinger-b** [comment]
Run `flatpak run org.signal.Signal` in the terminal.

This is also not an official distribution. I would argue that the AUR is more trustworthy because there is one fewer server involved.

**Comment by marcello42** [comment]
fair enough!

flatpak run org.signal.Signal -> would open the app wouldn't it?

**Comment by marcello42** [comment]
For anyone who has the same issue -> it is due to missing notifyd or similar. Signal freezes if there is no deamon taking the notifications.
