### ISSUE TITLE
Black screen on xwayland

### ISSUE THREAD

**Issue by alvarlagerlof** [flathub/org.signal.Signal#238]
![image](https://user-images.githubusercontent.com/14835120/141864908-cdce0491-d2a4-4a43-a33f-0f7c0c2f8eda.png)

**Comment by KissesRefined** [comment]
See is [these](https://github.com/signalapp/Signal-Desktop/issues/5361) [help](https://github.com/flathub/org.signal.Signal/issues/188#issuecomment-845746610).

TLDR: flatpak run org.signal.Signal --enable-features=UseOzonePlatform --ozone-platform=wayland + [socket access override]

**Comment by vchernin** [comment]
Nvidia?

**Comment by alvarlagerlof** [comment]
Shouldn't I work by default? Setting env vars is not nice. Yes, Nvidia.

**Comment by vchernin** [comment]
What distro? Make sure xwayland is up to date (21.1.3 or later iirc). It needed Nvidia-specific fixes for some xwayland apps to work.

**Comment by alvarlagerlof** [comment]
I don't think I have completely the latest, it's fedora 35. Will get GBM in a couple of days but this app was broken while other election apps worked, so I figured it was more likely incorrect options.

**Comment by vchernin** [comment]
You could try different options, but with GBM imminent it might be best just to wait.

**Comment by alvarlagerlof** [comment]
Yeah that might just fix it anyways. Will come back and report on it when it works/doesn't in a few days.

**Comment by alvarlagerlof** [comment]
The issue does not seem to be in the not in the drivers. I am now on 510 and the issue persists. GBM is supposed to have been working for a while. Using --disable-gpu-sandbox makes the app work.

**Comment by alvarlagerlof** [comment]
https://github.com/flathub/com.slack.Slack/issues/154 this might fix it

**Comment by vchernin** [comment]
Signal has `--device=all` which includes every device including `--device=dri`

**Comment by abique** [comment]
So it is a display thing in flatseal then.

**Comment by bermeitinger-b** [comment]
Can you test #277 ?

`flatpak install --user https://dl.flathub.org/build-repo/77479/org.signal.Signal.flatpakref`

**Comment by alvarlagerlof** [comment]
> Can you test #277 ?
> 
> `flatpak install --user https://dl.flathub.org/build-repo/77479/org.signal.Signal.flatpakref`

That just 404s, but --disable-gpu-sandbox did not work for me manually.

**Comment by abique** [comment]
I'm using the latest signal from flatpak and for me the bug is now fixed.

**Comment by alvarlagerlof** [comment]
> I'm using the latest signal from flatpak and for me the bug is now fixed.

It is indeed for me too.

![image](https://user-images.githubusercontent.com/14835120/157235461-014c3fba-30a9-4273-b0c3-3ce92e5abfb2.png)
