### ISSUE TITLE
The language has been reset to english with the new 5.29 update

### ISSUE THREAD

**Issue by Altonss** [flathub/org.signal.Signal#256]
Have you experienced the same? Is this related to this flatpak package or is this a signal bug in general?

**Comment by bermeitinger-b** [comment]
Seems to be an upstream issue and we'll have to wait for the next version: https://github.com/signalapp/Signal-Desktop/issues/5754

**Comment by Altonss** [comment]
> Seems to be an upstream issue and we'll have to wait for the next version: [signalapp/Signal-Desktop#5754](https://github.com/signalapp/Signal-Desktop/issues/5754)

Thank you very much! I'm sorry, I didn't looked upstream first :)
