### ISSUE TITLE
Tray Icon is blank since 5.29.0 update

### ISSUE THREAD

**Issue by r2rX** [flathub/org.signal.Signal#258]
Hello there,

I've got Signal Flatpak installed in Fedora 35 KDE. I edited the Exec entry in the shortcut with _--use-tray-icon_ ,since installing Signal a few weeks back, and has worked great over the last couple of updates. However, since the most recent update, an entry seems to be placed in the taskbar...but the icon itself is absent/missing.

![signal](https://user-images.githubusercontent.com/18622885/150646579-ac48f9f4-18ab-4b5b-8f12-33633538431e.jpg)

**Comment by r2rX** [comment]
Hi @bermeitinger-b . Here's the log when running `flatpak run org.signal.Signal --use-tray-icon`:

```
[xxxx@xxxx ~]$ flatpak run org.signal.Signal --use-tray-icon
[2 preload-host-spawn-strategy] Running: /app/bin/zypak-helper child - /app/Signal/signal-desktop --type=zygote --enable-crashpad
Set Windows Application User Model ID (AUMID) { appUserModelId: 'org.whispersystems.signal-desktop' }
NODE_ENV production
NODE_CONFIG_DIR /app/Signal/resources/app.asar/config
NODE_CONFIG {}
ALLOW_CONFIG_MUTATIONS undefined
HOSTNAME undefined
NODE_APP_INSTANCE undefined
SUPPRESS_NO_CONFIG_WARNING undefined
SIGNAL_ENABLE_HTTP undefined
userData: /home/xxxx/.var/app/org.signal.Signal/config/Signal
config/get: Successfully read user config file
config/get: Successfully read ephemeral config file
LaunchProcess: failed to execvp:
xdg-settings
LaunchProcess: failed to execvp:
xdg-settings
[2:0126/160712.956365:ERROR:bus.cc(393)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[2:0126/160713.007424:ERROR:bus.cc(393)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[2:0126/160713.007542:ERROR:bus.cc(393)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[2:0126/160713.007582:ERROR:bus.cc(393)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
[47:0126/160713.035497:ERROR:sandbox_linux.cc(376)] InitializeSandbox() called with multiple threads in process gpu-process.
(node:97) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `exe --trace-deprecation ...` to show where the warning was created)
```

**Comment by Cubevoid** [comment]
I am on Pop!_OS 21.10 using the GNOME 40 desktop. I am getting the same error as @r2rX and the icon is missing for me as well.

**Comment by TrusterX** [comment]
Signal 29.1 on Fedora 35:
![image](https://user-images.githubusercontent.com/6065454/151318992-6d05dcb3-bfb8-48b7-ae46-9946e7459a2b.png)

Terminal says:
> $ /usr/bin/flatpak run --branch=stable --arch=x86_64 --command=signal --file-forwarding org.signal.Signal @@u %U @@ --use-tray-icon
> [2 preload-host-spawn-strategy] Running: /app/bin/zypak-helper child - /app/Signal/signal-desktop --type=zygote --enable-crashpad
> Set Windows Application User Model ID (AUMID) { appUserModelId: 'org.whispersystems.signal-desktop' }
> NODE_ENV production
> NODE_CONFIG_DIR /app/Signal/resources/app.asar/config
> NODE_CONFIG {}
> ALLOW_CONFIG_MUTATIONS undefined
> HOSTNAME undefined
> NODE_APP_INSTANCE undefined
> SUPPRESS_NO_CONFIG_WARNING undefined
> SIGNAL_ENABLE_HTTP undefined
> userData: /home/somebody/.var/app/org.signal.Signal/config/Signal
> config/get: Successfully read user config file
> config/get: Successfully read ephemeral config file
> LaunchProcess: failed to execvp:
> xdg-settings
> LaunchProcess: failed to execvp:
> xdg-settings
> Gtk-Message: 09:13:26.978: Failed to load module "canberra-gtk-module"
> Gtk-Message: 09:13:26.978: Failed to load module "pk-gtk-module"
> Gtk-Message: 09:13:26.978: Failed to load module "canberra-gtk-module"
> Gtk-Message: 09:13:26.978: Failed to load module "pk-gtk-module"
> [2:0127/091327.015261:ERROR:bus.cc(393)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: Datei oder Verzeichnis nicht gefunden
> Failed to establish dbus connection[2:0127/091327.203971:ERROR:bus.cc(393)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: Datei oder Verzeichnis nicht gefunden
> [2:0127/091327.204140:ERROR:bus.cc(393)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: Datei oder Verzeichnis nicht gefunden
> [2:0127/091327.204271:ERROR:bus.cc(393)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: Datei oder Verzeichnis nicht gefunden
> (node:75) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
> (Use `exe --trace-deprecation ...` to show where the warning was created)

**Comment by salim-b** [comment]
On Ubuntu 20.04 (GNOME 3.36.8), the icon is not blank but looks weird since a recent update:

![Bildschirmfoto von 2022-01-27 16-29-24](https://user-images.githubusercontent.com/20040931/151391011-ffe03d6d-f755-4a22-8656-aa9d0fa70f15.png)

<details><summary>Startup command and output:</summary>

```
$ /usr/bin/flatpak run --branch=stable --arch=x86_64 --command=signal --file-forwarding org.signal.Signal @@u %U @@ --start-in-tray
[2 preload-host-spawn-strategy] Running: /app/bin/zypak-helper child - /app/Signal/signal-desktop --type=zygote --enable-crashpad
Set Windows Application User Model ID (AUMID) { appUserModelId: 'org.whispersystems.signal-desktop' }
NODE_ENV production
NODE_CONFIG_DIR /app/Signal/resources/app.asar/config
NODE_CONFIG {}
ALLOW_CONFIG_MUTATIONS undefined
HOSTNAME undefined
NODE_APP_INSTANCE undefined
SUPPRESS_NO_CONFIG_WARNING undefined
SIGNAL_ENABLE_HTTP undefined
userData: /home/salim/.var/app/org.signal.Signal/config/Signal
config/get: Successfully read user config file
config/get: Successfully read ephemeral config file
LaunchProcess: failed to execvp:
xdg-settings
LaunchProcess: failed to execvp:
xdg-settings
Gtk-Message: 16:31:07.513: Failed to load module "canberra-gtk-module"
Gtk-Message: 16:31:07.513: Failed to load module "canberra-gtk-module"
[2:0127/163107.532115:ERROR:bus.cc(393)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[2:0127/163107.588385:ERROR:bus.cc(393)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[2:0127/163107.588421:ERROR:bus.cc(393)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[2:0127/163107.588445:ERROR:bus.cc(393)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[48:0127/163107.641559:ERROR:sandbox_linux.cc(376)] InitializeSandbox() called with multiple threads in process gpu-process.
(node:99) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `exe --trace-deprecation ...` to show where the warning was created)
```

</details>

**Comment by bermeitinger-b** [comment]
Unfortunately, the log doesn't say much. Do you all use Wayland?

**Comment by hhl** [comment]
Hi, not using wayland, but I also have that problem with no icon, if I start from tty/console `flatpak run org.signal.Signal --use-tray-icon`
I see a strange wired looking (fallback?) icon and the same output as above!
What I see in that output is 
```
LaunchProcess: failed to execvp:
xdg-settings
LaunchProcess: failed to execvp:
xdg-settings
```
Maybe something changed?

**Comment by vasyugan** [comment]
I my case, I don't see nothing but a three dots menu. But as for everyone else, it worked fine until a few days ago. 
![grafik](https://user-images.githubusercontent.com/3313208/151542242-e7fea394-9353-4e4d-ae71-d54670bc2f72.png)

**Comment by salim-b** [comment]
> Unfortunately, the log doesn't say much. Do you all use Wayland?

No, X11 (still the default in Ubuntu 20.04).

**Comment by vasyugan** [comment]
BTW, I see the same issue in MATE, which is still using X11

**Comment by bermeitinger-b** [comment]
Can anyone test the test version from #264 ?

`flatpak install --user https://dl.flathub.org/build-repo/74102/org.signal.Signal.flatpakref`

**Comment by salim-b** [comment]
> Can anyone test the test version from #264 ?
> 
> ```
> flatpak install --user https://dl.flathub.org/build-repo/74102/org.signal.Signal.flatpakref
> flatpak run --user --branch=test org.signal.Signal --use-tray-icon
> ```

No difference for me, i.e. still the same [broken icon](https://github.com/flathub/org.signal.Signal/issues/258#issuecomment-1023342828).

<details><summary>Startup command and output:</summary>

```
$ flatpak run --user --branch=test org.signal.Signal --use-tray-icon
[2 preload-host-spawn-strategy] Running: /app/bin/zypak-helper child - /app/Signal/signal-desktop --type=zygote --enable-crashpad
Set Windows Application User Model ID (AUMID) { appUserModelId: 'org.whispersystems.signal-desktop' }
NODE_ENV production
NODE_CONFIG_DIR /app/Signal/resources/app.asar/config
NODE_CONFIG {}
ALLOW_CONFIG_MUTATIONS undefined
HOSTNAME undefined
NODE_APP_INSTANCE undefined
SUPPRESS_NO_CONFIG_WARNING undefined
SIGNAL_ENABLE_HTTP undefined
userData: /home/salim/.var/app/org.signal.Signal/config/Signal
config/get: Successfully read user config file
config/get: Successfully read ephemeral config file
LaunchProcess: failed to execvp:
xdg-settings
LaunchProcess: failed to execvp:
xdg-settings
Gtk-Message: 14:00:51.389: Failed to load module "canberra-gtk-module"
Gtk-Message: 14:00:51.389: Failed to load module "canberra-gtk-module"
[2:0128/140051.407631:ERROR:bus.cc(393)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[2:0128/140051.478287:ERROR:bus.cc(393)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[2:0128/140051.478328:ERROR:bus.cc(393)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[2:0128/140051.478352:ERROR:bus.cc(393)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[47:0128/140051.514487:ERROR:sandbox_linux.cc(376)] InitializeSandbox() called with multiple threads in process gpu-process.
(node:133) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `exe --trace-deprecation ...` to show where the warning was created)
```

</details>

**Comment by vasyugan** [comment]
> Can anyone test the test version from #264 ?
> 
> ```
> flatpak install --user https://dl.flathub.org/build-repo/74102/org.signal.Signal.flatpakref
> flatpak run --user --branch=test org.signal.Signal --use-tray-icon
> ```

No improvement, unfortunately.

Console output:

```
Installation complete.
[2 preload-host-spawn-strategy] Running: /app/bin/zypak-helper child - /app/Signal/signal-desktop --type=zygote --enable-crashpad
Set Windows Application User Model ID (AUMID) { appUserModelId: 'org.whispersystems.signal-desktop' }
NODE_ENV production
NODE_CONFIG_DIR /app/Signal/resources/app.asar/config
NODE_CONFIG {}
ALLOW_CONFIG_MUTATIONS undefined
HOSTNAME undefined
NODE_APP_INSTANCE undefined
SUPPRESS_NO_CONFIG_WARNING undefined
SIGNAL_ENABLE_HTTP undefined
userData: /home/jr/.var/app/org.signal.Signal/config/Signal
config/get: Successfully read user config file
config/get: Successfully read ephemeral config file
LaunchProcess: failed to execvp:
xdg-settings
LaunchProcess: failed to execvp:
xdg-settings
Gtk-Message: 14:20:16.768: Failed to load module "canberra-gtk-module"
Gtk-Message: 14:20:16.768: Failed to load module "canberra-gtk-module"
[2:0128/142016.922066:ERROR:bus.cc(393)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: Datei oder Verzeichnis nicht gefunden
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
[47:0128/142018.953177:ERROR:sandbox_linux.cc(376)] InitializeSandbox() called with multiple threads in process gpu-process.
[2:0128/142018.986106:ERROR:bus.cc(393)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: Datei oder Verzeichnis nicht gefunden
[2:0128/142018.986146:ERROR:bus.cc(393)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: Datei oder Verzeichnis nicht gefunden
[2:0128/142018.986167:ERROR:bus.cc(393)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: Datei oder Verzeichnis nicht gefunden
(node:76) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `exe --trace-deprecation ...` to show where the warning was created)


```

**Comment by r2rX** [comment]
> Unfortunately, the log doesn't say much. Do you all use Wayland?

Wayland is running on my system. Unfortunately, the #264 test version produces the same result.

**Comment by bermeitinger-b** [comment]
Could you test again?

`flatpak install --user https://dl.flathub.org/build-repo/74131/org.signal.Signal.flatpakref`

This works on a new Manjaro XFCE VM.

**Comment by salim-b** [comment]
> Could you test again?
>
> `flatpak install --user https://dl.flathub.org/build-repo/74131/org.signal.Signal.flatpakref`

Awesome, works fine on Ubuntu 20.04 (X11)! :tada:

**Comment by bermeitinger-b** [comment]
Perfect.

**Comment by r2rX** [comment]
> Could you test again?
> 
> `flatpak install --user https://dl.flathub.org/build-repo/74131/org.signal.Signal.flatpakref`
> 
> This works on a new Manjaro XFCE VM.

Can confirm this works now. Thanks alot @bermeitinger-b !
