### ISSUE TITLE
Custom Compose key sequences don't work in Signal

### ISSUE THREAD

**Issue by m93a** [flathub/org.signal.Signal#259]
I use Compose key with custom sequences defined in `~/XCompose`. I can use these sequences in all apps (even Flatpak ones) except for Signal. In Signal, compose key works, but only the default predefined sequences are available.

As a walkaround, I have to switch to a different app, type the symbols I need, copy them, switch back to Signal, and paste. Doing this several times a day gets a bit annoying, so if there was a way to resolve this, I'd love it.

**Comment by bermeitinger-b** [comment]
Which other Flatpak apps allow this feature so that we can adapt it here?

**Comment by m93a** [comment]
I'm not sure which other apps do this, but running the following command fixed my issue:
```zsh
flatpak override org.signal.Signal --filesystem=/home/csha/.XCompose
```

**Comment by bermeitinger-b** [comment]
Yes, well, that's the problem with sandboxing. You can't get out of it. Thank you for posting the answer.

The security considerations were too strict many users here that the access is only allowed to certain folders by default. (#153, #154, #181, #182, #183, #185)

**Comment by kierun** [comment]
I have the same issue and 
`flatpak override org.signal.Signal --filesystem=/home/user/.XCompose` does nothing for me. I had to use `sudo` to get it to even run.

```bash
√ ; bat /var/lib/flatpak/overrides/org.signal.Signal
───────┬────────────────────────────────────────────────────────────────────────
       │ File: /var/lib/flatpak/overrides/org.signal.Signal
───────┼────────────────────────────────────────────────────────────────────────
   1   │ [Context]
   2   │ filesystems=home;/home/user/.XCompose;
───────┴────────────────────────────────────────────────────────────────────────
```
