### ISSUE TITLE
Remove filesystem permissions?

### ISSUE THREAD

**Issue by vchernin** [flathub/org.signal.Signal#260]
As of https://github.com/flathub/org.signal.Signal/commit/e5e21bb55a2cf2aca5c4eb01b2c402858bf23eb5 the filechooser portal is used for selecting files thanks to upstream electron support. So filesystem permissions are no longer needed for that.

Unfortunately, drag and drop with the filetransfer portal is not yet supported in electron, or current file manager apps. So for that you'd still need the permissions.

Should this just be left alone until drag and drop also works?

**Comment by Altonss** [comment]
This PR seems to "partly" resolve this issue https://github.com/flathub/org.signal.Signal/pull/334
