### ISSUE TITLE
Drop --filesystem=xdg-run/pipewire-0 from manifest

### ISSUE THREAD

**Issue by rmader** [flathub/org.signal.Signal#261]
The fact that screen sharing on Wayland required Pipewire socked access despite using the xdg portal was a [WebRTC bug](https://webrtc-review.googlesource.com/c/src/+/230803). Once the fix has reached the electron version used by signal, --filesystem=xdg-run/pipewire-0 can be dropped.

See also:
- https://github.com/flathub/org.jitsi.jitsi-meet/issues/31
- https://github.com/flathub/org.chromium.Chromium/issues/148
- https://github.com/flathub/com.slack.Slack/issues/147

**Comment by vchernin** [comment]
Unfortunately this doesn't even work due to https://github.com/signalapp/Signal-Desktop/issues/5350 :(

But yes it should be removed in any case.

**Comment by Altonss** [comment]
So the not-working screen sharing on the signal flatpak on wayland is not an issue with the flatpak but the the signal software itself?

**Comment by vchernin** [comment]
> So the not-working screen sharing on the signal flatpak on wayland is not an issue with the flatpak but the the signal software itself?

Yes
