### ISSUE TITLE
"Set up as new device" never finishes loading, and does not show a QR Code.

### ISSUE THREAD

**Issue by Gooseheaded** [flathub/org.signal.Signal#263]
* **Laptop:** ThinkPad X1 Yoga 4th
  * **OS + Kernel:** Arch Linux, 5.16.2-arch1-1
  * **Signal version:** 5.29.1
  * **Flatpak version:** 1.12.4
  * **Debug Logs:** https://debuglogs.org/d1c1caecec313fd0132e07c1b1ef3982e4c4949d7fc3bd827cbfac35931e875b.gz

When I open the desktop app and click on "Set up as new device," I am shown the loading screen where the QR Code should appear. However, the loading screen never finishes loading, so the QR Code is never shown, making it impossible to pair my phone with this computer.

I have searched for similar issues on this github project, as well as Signal's own github (https://github.com/signalapp/Signal-Desktop/). The only issues that were similar seem to have been caused either by network issues (https://github.com/signalapp/Signal-Desktop/issues/4465), or by some sort of unresponsive UI (https://github.com/signalapp/Signal-Desktop/issues/4017).

In my case, the app remain fully responsive as I can still edit my preferences, check the version, etc. This is a fairly modern laptop connected to my home Wi-Fi, and there are no unusual network configurations involved (eg. VPNs or proxies).

I have tried restarting the app, reinstalling the app, and rebooting the computer. This error also occurs on the (non-flatpak) version of Signal on Arch Linux's official repos.

I have not noticed anything unusual about this computer. The debug logs do not appear to show any errors (logs are linked above). I have not seen similar abnormalities in other apps. 

Thank you!

**Comment by Altonss** [comment]
Are you still experiencing this issue?

**Comment by Gooseheaded** [comment]
Hmm. As a matter of fact, I am not! I opened the app now, and it is working.

I do not recall doing any sort of Signal-specific maintenance or configuration since I originally created this issue. I have only kept my Arch installation, as a whole, up to date.

**Comment by Altonss** [comment]
It was maybe an upstream issue with Signal itself, but great to hear it is now resolved :+1:
