### ISSUE TITLE
permissions of file chooser portal

### ISSUE THREAD

**Issue by eike-fokken** [flathub/org.signal.Signal#267]
I have locked down my signal-desktop to have permissions only in a specific folder.

Funnily enough these permissions are honored if I download a file sent to me. I can only access the specific directory I gave permissions to.
If I instead want to choose a file to send, the filechooser gives me access to my whole home directory. I get that this works as intended even though I strongly dislike that.

Yet what I think is a bug (not sure if it is here, maybe the filechooser api just doesn't provide finegrained access control) is this:

When I have chosen a file to send, not only is access to that file granted indefinitely,
```sh
flatpak permission-show org.signal.Signal
Table     Object   App               Permissions                  Data
documents 1234dc3e org.signal.Signal read,write,grant-permissions (b'/home/eike/testsignal.txt', 2052, 5642088, 0)
```

but if I understand that output right, then indeed signal-desktop has gotten write access.
Is there a different filechooser api to only request read access for sending files? If so that would probably be a better choice.

Also can signal prevent the indefinite permission?

**Comment by eike-fokken** [comment]
> When you select a file, that particular file is passed to the app.

Not sure if we mean the same: The file is not passed in the sense of "copied to a location accessible to the app", if I understand all that correctly, but rather, signal-desktop is granted access to the file chosen in the filechooser dialog indefinitely and apparently (see the output of `flatpak permission-show org.signal.Signal` above) the access is read write.

 Could signal-desktop invoke another part of the filechooser api to prevent getting write access?

**Comment by vchernin** [comment]
At least for me on Fedora with xdg-desktop-portal-gnome, the file picker has a "open files read-only" checkbox in the bottom left which I think addresses your concern. 

However, `flatpak permission-show` shows the files are writable regardless. That's likely a portal bug of some kind.

**Comment by Altonss** [comment]
Is this PR https://github.com/flathub/org.signal.Signal/pull/334 solving this issue? It sets directories as read-only (initially just for the drag and drop permissions I think)

**Comment by eike-fokken** [comment]
It sounds relevant, but I havn't had the time to test it. I hope I'll get to it.

**Comment by Maltimore** [comment]
I have just tested the above steps and for me signal doesn't have any read/write access it seems:

```
$ flatpak permission-show org.signal.Signal
Table      Object     App               Permissions Data
background background org.signal.Signal yes         0x00
```

**Comment by bermeitinger-b** [comment]
According to #438 , you don't need to set access permissions. They will be granted by the portal.
