### ISSUE TITLE
Please gpg verify fetched debs

### ISSUE THREAD

**Issue by Esokrates** [flathub/org.signal.Signal#27]
From what I see in the json file under "sources", you simply download the deb from Signal's server and only check the sha256 sum.

Please make sure you gpg verify the downloaded file!

**Comment by Esokrates** [comment]
If this is not supported, please tell me which component I should file the bugs against?

**Comment by nedrichards** [comment]
you should raise against https://github.com/flatpak/flatpak asking for gpg verification for extra-data.
