### ISSUE TITLE
Doesnt start on Wayland, Kubuntu with Backports

### ISSUE THREAD

**Issue by firefoxlover** [flathub/org.signal.Signal#270]
The client doesnt start on Wayland, I guess it doesnt work yet.

Operating System: Kubuntu 21.10
KDE Plasma Version: 5.23.5
KDE Frameworks Version: 5.90.0
Qt Version: 5.15.2
Kernel Version: 5.13.0-28-generic (64-bit)

**Comment by bermeitinger-b** [comment]
Closed in favor of #269
