### ISSUE TITLE
Version number bug

### ISSUE THREAD

**Issue by Altonss** [flathub/org.signal.Signal#282]
I just received the Signal 5.36 update through flathub and it seems the 5.35 version  update has been skipped.
This error might be the reaseon why the 5.36 version is numbered 5.35 in flathub and my gnome software...

**Comment by bermeitinger-b** [comment]
Signal itself shows 5.36.0, the [metainfo.xml](https://github.com/flathub/org.signal.Signal/blob/87c6d73c6098749078f34b00636d88c7d3b94cba/org.signal.Signal.metainfo.xml#L39) shows 5.36.0, and [Flathub's page](https://flathub.org/apps/details/org.signal.Signal) shows 5.36.0. 🤷

**Comment by Altonss** [comment]
Oh my bad, I just restarted Gnome software and it now appears correctly, and it appears correctly when doing flatpak list.
Sorry :laughing:
