### ISSUE TITLE
Confusion about startup of Flatpak

### ISSUE THREAD

**Issue by brianredbeard** [flathub/org.signal.Signal#284]
While reviewing [#280](https://github.com/flathub/org.signal.Signal/issues/280#issuecomment-1070981694) there was a mention of changes to `.desktop` files.  Digging into this further I see that a few days ago changes were made to `signal-desktop.sh` by @bermeitinger-b, but it looks as if the `.desktop` file was never updated to use this shell wrapper (https://github.com/flathub/org.signal.Signal/blame/87c6d73c6098749078f34b00636d88c7d3b94cba/org.signal.Signal.yaml#L53).  

Is the intention that the `.desktop` file use this shell wrapper? If not in what situations is the shell wrapper intended to be used?

-----
Potentially affects #283

**Comment by bermeitinger-b** [comment]
I might be wrong but it installs the `signal-desktop.sh` as `signal-desktop`: https://github.com/flathub/org.signal.Signal/blob/87c6d73c6098749078f34b00636d88c7d3b94cba/org.signal.Signal.yaml#L45 
This is then called by your quoted line.

At least this is the intended behavior.

**Comment by brianredbeard** [comment]
Thanks for clarifying that.  I missed that line while double checking #280.  I can confirm it's working as intended:

```bash
[/var/lib/flatpak/app/org.signal.Signal/x86_64/stable/active/files]$ head bin/signal-desktop 
#!/bin/bash

EXTRA_ARGS=()

if [[ -z "${DISPLAY}" ]] && [[ -n "${WAYLAND_DISPLAY}" ]];
then
    EXTRA_ARGS+=(
        "--enable-features=UseOzonePlatform"
        "--ozone-platform=wayland"
        "--disable-gpu"
```
The process of changing the name of the file using `install` threw me off.
