### ISSUE TITLE
Flatpak Update 5.37.0 will not start on Linux Mint 19.3 Cinnamon

### ISSUE THREAD

**Issue by aibnsamin** [flathub/org.signal.Signal#288]
**Bug Description**

After updating to 5.37.0, cannot start Signal from GUI or CLI.

**Actual Result**

Signal background processes start but the app never starts with GUI.

$`sudo flatpak run org.signal.Signal/x86_64/stable

flatpak run: Can't get document portal: GDBus.Error:org.freedesktop.DBus.Error.Spawn.ChildExited: Process org.freedesktop.portal.Documents exited with status 2
[2 zypak-helper] Failed to connect to session bus: [org.freedesktop.DBus.Error.NotSupported] Using X11 for dbus-daemon autolaunch was disabled at compile time, set your DBUS_SESSION_BUS_ADDRESS instead
[2 zypak-helper] src/helper/main.cc:40(DetermineZygoteStrategy): Assertion failed: bus

**Expected Result**

Signal boots and it can be used.

**Platform Info**
Signal Desktop version: 5.37.0

**Operating System:**
Linux Mint 19.3 Cinnamon

**Comment by bermeitinger-b** [comment]
Why would you run it as root?

**Comment by aibnsamin** [comment]
No particular reason, just want to ensure it has proper permissions

**Comment by aibnsamin** [comment]
If I remove sudo:

flatpak run org.signal.Signal/x86_64/stable 
[2 zypak-helper] Error retrieving supports property: org.freedesktop.DBus.Error.InvalidArgs: No such property 'supports'
[2 zypak-helper] Portal v4 is not available
Set Windows Application User Model ID (AUMID) { appUserModelId: 'org.whispersystems.signal-desktop' }
NODE_ENV production
NODE_CONFIG_DIR /app/Signal/resources/app.asar/config
NODE_CONFIG {}
ALLOW_CONFIG_MUTATIONS undefined
HOSTNAME undefined
NODE_APP_INSTANCE undefined
SUPPRESS_NO_CONFIG_WARNING undefined
SIGNAL_ENABLE_HTTP undefined
userData: /home/abulut/.var/app/org.signal.Signal/config/Signal
config/get: Successfully read user config file
config/get: Successfully read ephemeral config file
LaunchProcess: failed to execvp:
xdg-settings
LaunchProcess: failed to execvp:
xdg-settings
[2:0406/171643.013774:ERROR:bus.cc(393)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory

**Comment by aibnsamin** [comment]
I was able to revert it to an older commit and it worked for a while, but today it stopped. I reverted it to a much older commit and it prompted me to wipe the database. When I did, it deleted my account history and started with a QR code screen. Essentially, the desktop flatpak seems to be totally broken on Mint.

**Comment by aibnsamin** [comment]
Strangely enough, after it updated, it broke again. I just started it and forgot about it. About 2 hours later the app launched. I am hesitant to close the issue until I see what the behavior is going forth.
