### ISSUE TITLE
If an added file's name is long enough, the message will be wider than the conversation window

### ISSUE THREAD

**Issue by K4LCIFER** [flathub/org.signal.Signal#291]
OS: Arch Linux
DE: Gnome 42.0 Wayland

As seen in the image, The added file is wider than the chat, and is thus obscured by the side panel.
![image](https://user-images.githubusercontent.com/7829231/162381935-abfccb3d-15f3-4db3-af89-afd84b88fc7f.png)

**Comment by bermeitinger-b** [comment]
I don't think this is a specific flatpak issue, or is it?

**Comment by K4LCIFER** [comment]
It most likely isn't, but when I initially went to submit this on the signal-desktop issue tracker, the issue template said to first post it here since I installed it through flatpak.

**Comment by bermeitinger-b** [comment]
This can't be fixed by us.

**Comment by K4LCIFER** [comment]
Alright, sounds good. I'll move it over to the signal-desktop GitHub repo.
