### ISSUE TITLE
System theme does not follow well, the system theme

### ISSUE THREAD

**Issue by igalic** [flathub/org.signal.Signal#293]
Setting Appearance ⇒ Theme ⇒ System does not follow the system theme.

On my Elementary system, which switches from Light theme during day to dark theme during night hours, Signal's "system" theme stays light.

**Comment by Altonss** [comment]
This seems to be an "upstream" Signal desktop issue (not related to flatpak for the moment):
See here https://github.com/signalapp/Signal-Desktop/issues/5155 and also related to https://github.com/signalapp/Signal-Desktop/issues/5091
For now I think, we could close the issue?

**Comment by igalic** [comment]
Thanks for the update.
