### ISSUE TITLE
Wayland's support requires disabling X11 socket

### ISSUE THREAD

**Issue by eaglesemanation** [flathub/org.signal.Signal#295]
## Problem

https://github.com/flathub/org.signal.Signal/blob/16e39c16c22107039226eae141a7d5ad6f3ed9a8/signal-desktop.sh#L5

Currently, to enable wayland native support, there is a check of $DISPLAY env var.

https://github.com/flathub/org.signal.Signal/blob/16e39c16c22107039226eae141a7d5ad6f3ed9a8/org.signal.Signal.yaml#L15

X11 is provided by default and this env variable is always defined, as long as XWayland is installed. Because of this I had to turn off X11 socket through FlatSeal on my machine to get nicely rendered fonts.

## Suggested fix

https://github.com/flathub/org.signal.Signal/blob/16e39c16c22107039226eae141a7d5ad6f3ed9a8/signal-desktop.sh#L15

Maybe we could use [XDG_SESSION_TYPE](https://xdg.freedesktop.narkive.com/Hv52Hf7B/question-about-the-session-type-environmental-variable) variable. I'm not sure how reliable this approach is, but you are already using it, so I'm assuming it works.

**Comment by bermeitinger-b** [comment]
Could you test #296 ?

(I don't know why this split was there in the first place, I guess checking for `XDG_SESSION_TYPE` should be enough. I can't test this extensively because I neither have Wayland nor Nvidia.)

**Comment by eaglesemanation** [comment]
```
Debug: Will run signal with the following arguments: --ozone-platform=wayland --enable-features=UseOzonePlatform --enable-features=WaylandWindowDecorations --disable-gpu
Debug: Additionally, user gave: 
...
```

Fonts look sharp with fractional scaling, so I think it works correct

**Comment by bermeitinger-b** [comment]
Perfect, thanks. We'll see how it goes.

**Comment by bermeitinger-b** [comment]
This didn't work out so well. #297

**Comment by bermeitinger-b** [comment]
With the new upstream versions, I was able to run it in Gnome Wayland with the settings. We'll try again with #301
