### ISSUE TITLE
Latest update (today) just broke the full screen

### ISSUE THREAD

**Issue by Altonss** [flathub/org.signal.Signal#297]
I belived I already had 5.38.0 since a few days, but just received another update just now, and I noticed the fullscreen is now broken (on Fedora 35, Gnome). The window doesn't open full screen anymore, some "space"/"padding" remains around the borders...
Has anyone experienced the same?

**Comment by bermeitinger-b** [comment]
The latest update should have fixed everything (yeah lol) about Wayland.

Could you provide a screenshot, the log from starting from terminal, and you are 100% sure that it didn't occur as of yesterday?

**Comment by Altonss** [comment]
It started with the last update today, difficult to provide a screenshot as it contains rather personnal information :) And the log doesn't seem very informative...

**Comment by Altonss** [comment]
Signal is now really unstable, crashes and has visual glitches. I will try to turn off the tray icon to see if it solves the issue.

**Comment by Altonss** [comment]
Here a screenshot 
![image](https://user-images.githubusercontent.com/66519591/162639489-cfe7d0b2-a6f0-44ea-93b9-a2c241d04612.png)

**Comment by ethanbowering24** [comment]
> The latest update should have fixed everything (yeah lol) about Wayland.
> 
> Could you provide a screenshot, the log from starting from terminal, and you are 100% sure that it didn't occur as of yesterday?

Similar story here, used signal this morning on my laptop. Got a notification that flatpak had updated signal. Opened it up and although it is still usable, fullscreen no longer works properly with strange padding around the window, and the UI scaling is off. I have censored my chats, they appear fine though.

![image](https://user-images.githubusercontent.com/61316561/162640181-0fd307cd-9d2c-4c6c-b530-88eb77bb2049.png)

**Comment by ethanbowering24** [comment]
> > The latest update should have fixed everything (yeah lol) about Wayland.
> > Could you provide a screenshot, the log from starting from terminal, and you are 100% sure that it didn't occur as of yesterday?
> 
> Similar story here, used signal this morning on my laptop. Got a notification that flatpak had updated signal. Opened it up and although it is still usable, fullscreen no longer works properly with strange padding around the window, and the UI scaling is off. I have censored my chats, they appear fine though.
> 
> ![image](https://user-images.githubusercontent.com/61316561/162640181-0fd307cd-9d2c-4c6c-b530-88eb77bb2049.png)

Trying to manipulate the window just locked up my whole system. Couldn't even crtl alt fx into a different TTY

**Comment by Altonss** [comment]
Have experienced the same glitches :)

**Comment by ethanbowering24** [comment]
Downgrading to commit from April 8th fixes my issue, like this guide

https://docs.flatpak.org/en/latest/tips-and-tricks.html?highlight=downgrade

`sudo flatpak update --commit=9c0cbb69aaa663403f7d8dedceed5d7d9a3cc97a31f8060a07ea570cb81fc430 org.signal.Signal` to downgrade, followed by

`flatpak mask org.signal.Signal` to prevent auto updates.

**Comment by GlenMerlin** [comment]
On my system signal opens for a fraction of a second before crashing my entire DE and softlocking my computer same update version

**Comment by Summertime** [comment]
whenever resizing the window, the window would seemingly close itself and be unrecoverable (I don't have a tray icon extension atm)

**Comment by bermeitinger-b** [comment]
These seem to be different issues. I can reproduce the gaps for the fullscreen. Apparently, at some point electron and/or chromium changed something. I'll revert the wayland fixes which will remove specific fixes but it'll not crash at least I guess.

**Comment by Altonss** [comment]
The problem has been fixed, so I will close the issue. Thanks @bermeitinger-b :)

**Comment by somoant** [comment]
probably it's electron/chromium bug https://github.com/electron/electron/issues/33161
