### ISSUE TITLE
Order of releases seems to be important

### ISSUE THREAD

**Issue by bermeitinger-b** [flathub/org.signal.Signal#3]
Judging from the Buildbot's output on [Build 994](https://flathub.org/builds/#/builders/1/builds/994), the order of the releases must be in descending date.

So, instead of:
https://github.com/flathub/org.signal.Signal/blob/81aef9210b6aab3f4c92fd5aa943c51601ab4f54/org.signal.Signal.appdata.xml#L23-L27
it should be:
```xml
  <releases>
    <release version="1.0.38" date="2017-11-15"/>
    <release version="1.0.37" date="2017-11-08"/>
    <release version="1.0.35" date="2017-11-01"/>
  </releases>
```

**Comment by Barthalion** [comment]
Oops, I forgot to push it. Thanks!
