### ISSUE TITLE
Release console started from

### ISSUE THREAD

**Issue by r-cheologist** [flathub/org.signal.Signal#30]
Other than e.g. `com.skype.Client`, `org.signal.Signal` opens the applicaton window, but keeps a hold of the console it was started from, continuously printing debugging messages.

Can that behavior be modified such that after starting the application, the starting CLI returns to a prompt and debugging output is suppressed?

**Comment by nedrichards** [comment]
This is an issue for https://github.com/flatpak/flatpak isn't it?

**Comment by bermeitinger-b** [comment]
Couldn't you use `flatpak run org.signal.Signal &` to run send it to the background? 
I, for example, would like to see debug messages.

**Comment by barthalion** [comment]
If it works with Skype, but doesn't with Signal then you should report it upstream as it's not related to flatpak.

**Comment by r-cheologist** [comment]
I understand that the debug messages may be helpful under some conditions, but that should be fakultative, as the 'average' user probably doesn't want them ...
Also: I have been using signal in a bunch of other incarnations before gravitating to the flatpak option (mainly as a solution to run app-specific VMs within QubesOs without installing to the template) and have never seen the problem before - I thus strongly suspect it's a packaging artifact.

**Comment by r-cheologist** [comment]
See [this](https://github.com/flathub/org.signal.Signal/issues/31).

**Comment by r-cheologist** [comment]
`flatpak run org.signal.Signal &` is no real mitigation - the console is conceptually usable again, but any reasonable use drowns in the deluge of log messages printed.
