### ISSUE TITLE
Can I trust this non-official app as much as the official .deb?

### ISSUE THREAD

**Issue by Vite** [flathub/org.signal.Signal#300]
Hey, thanks for maintaining a flatpak version of Signal Desktop for Linux.
Since I am on Fedora I need to use this non-official app.

I have strong concerns about this app being safe to use since it is non-official.
Are there any things I have to trust the repo maintainer with? If so, can I change this as a casual user?
If so, with what do I trust the repo maintainer? What are the potential risks of using this non-official version instead of the official one?
Are there safer (lower trust) ways to install Signal-Desktop on Fedora, by for example disabling auto-update of this Flatpak App?

Feel free to close this issue, if this topic does not belong here.

**Comment by bermeitinger-b** [comment]
What is your attack scenario? You can only be safe _against_ something.

We had a similar discussing already in #171 about the update process.

If you want a trust scale, then no, this repackaging requires more trust of the user than the deb file.

* Anyone with master access/maintainer status can arbitrarily change any file in the repo, e.g. replace the url of the deb to a malicious one. (Well, or GitHub could probably modify any file, it's their servers.)
* The server that builds the flatpak is run by Flathub. It downloads the build script, runs the commands (meaning downloading the deb file), extracting it, and copying things around. A rogue build server could arbitrarily modify any file.

For the first one, you could check the commits, especially if the URL to the deb points to the correct location.
The second one can be circumvented by building the flatpak yourself with flatpak-builder, so you are removing flathub from the equation. (However, it will still download the build/runtime requirements from flathub.)

If you don't trust flatpak itself, you could build it yourself using the arch's [PKGBUILD](https://aur.archlinux.org/packages/signal-desktop-beta).

But again, what security issue do you have and who is your attacker?
