### ISSUE TITLE
Drag and Drop of attachments doesn't work

### ISSUE THREAD

**Issue by puenka** [flathub/org.signal.Signal#307]
On my Ubuntu 22.04 with Signal 5.42.0 from flathub, dragging a file from GNOME Files into a chat does not work. I get the error "Unable to load selected attachment". Using the + symbol to add the attachment for the same file at the same location works.

**Comment by bermeitinger-b** [comment]
Do you maybe have Wayland?

**Comment by puenka** [comment]
It doesn't seem to work on either, but on X11 I get the message stated above, on Wayland it simply doesn't do anything.

**Comment by lkiesow** [comment]
I can confirm this on Fedora 35 Cinnamon which is still using X11

**Comment by JYPDWhite** [comment]
I also can confirm it's not working Arch Linux with KDE (and X11)

**Comment by JYPDWhite** [comment]
@chamdim  that's a cool workaround but I think the flatpak should be provided with this access rights out of the box.

**Comment by puenka** [comment]
Thanks for the workaround. I then suggest an improved error message (or an error message in the first place) instead of silently failing.

**Comment by bermeitinger-b** [comment]
As per #153 this is working as intended.
