### ISSUE TITLE
Silence the log messages

### ISSUE THREAD

**Issue by da2x** [flathub/org.signal.Signal#31]
I’ve left Signal running for weeks and hours. The problem ios that upstream prints a message to the console every six seconds. I now have gigabytes of log data of useless keepalives. Upstream [rejected an related patch](https://github.com/signalapp/Signal-Desktop/pull/2138) for log messages printed every 55 seconds.

Can the Flatpak be updated to discard messages instead of sending them to the journal?

1. Run Signal
2. Keep an eye on `journalctl -ef`

**Comment by janvlug** [comment]
Could this be related to [this issue](https://github.com/signalapp/Signal-Desktop/issues/2733), where I in the comments describe the excessive logging by Signal in the journal? I'm on fully updated Fedora 29, using the Signal Desktop flatpak.

**Comment by janvlug** [comment]
I opened a [topic](https://community.signalusers.org/t/how-to-stop-flatpak-signal-desktop-from-logging-to-system-logs/6323) on the Signal community forum to discuss this issue.

**Comment by janvlug** [comment]
At the moment on a fully up-to-date powerful Fedora 30 desktop system running Gnome on Wayland, I experience the following after the systems wakes up from suspend. Signal Desktop was running when the system was suspended. During the suspend period, I sent and received a bunch of Signal messages via another device:

1. I see the unlock/login screen with a list of user names to log in.
2. I select my user name to resume the previous desktop session.
3. I enter my password, when I hit the "Enter" key, the system freezes for a while (sometimes a few minutes). During this freeze, the pointer stops spinning and the pointer cannot be moved any more with the mouse. During the freeze, I still see the screen where I entered my password.
3. After a while the system unlocks the desktop session, and everything works fine.

I inspected the log files in an attempt to find the cause of this temporary freeze. In the journal I see loads of Signal log messages. [See attached journal file.](https://github.com/flathub/org.signal.Signal/files/3219251/temp_freeze_after_resume.txt) At the time of the last Signal log message, the system roughly unfroze.

I suspect that the logging by Signal causes this temporary freeze. I also think this is one of the root reasons for issue: https://github.com/signalapp/Signal-Desktop/issues/3010

**Comment by janvlug** [comment]
The slowness was caused by not running fstrim on my SSD, see: https://github.com/signalapp/Signal-Desktop/issues/3671#issuecomment-699609685.

I do not see the spurious log messages any more in the system logs.

Therefore, this issue can be closed.
