### ISSUE TITLE
Cannot register new Linux device

### ISSUE THREAD

**Issue by sebastiankirsch** [flathub/org.signal.Signal#310]
Hey, I've freshly set up my laptop w/ Ubuntu 22.04 and installed signal-desktop via Ubuntu Software/snap.
When starting the Signal desktop app, the QR code won't load, thus I cannot do anything.

Here's the debug log: https://debuglogs.org/desktop/5.38.0/0b1287ac70d3983c1d28eb9d98d4fdc813c3e2d5915210275b787c8eccdad07f.gz

**Comment by bermeitinger-b** [comment]
This repo is about Flatpak.

**Comment by sebastiankirsch** [comment]
> This repo is about Flatpak.

I see. Then maybe ask the folks at [signalapp/Signal-Desktop](https://github.com/signalapp/Signal-Desktop) to adapt their [issue template](https://github.com/signalapp/Signal-Desktop/issues/new?assignees=&labels=&template=bug_report.md&title=)...

Sorry for the noise.
