### ISSUE TITLE
Unhandled Promise Rejection - Application Won't Launch

### ISSUE THREAD

**Issue by linuxosd** [flathub/org.signal.Signal#314]
Version 5.44.1 on Manjaro Linux KDE.

Launching application displays a window with this error:
![signalerror](https://user-images.githubusercontent.com/81487885/170782510-e4fb3f66-74ad-4dbf-baae-403eff7b210c.png)

**Comment by bermeitinger-b** [comment]
Looks like your database is corrupt. I don't think this has something to do with the flatpak version and you're better off asking for support in the upstream repo.
