### ISSUE TITLE
Idle CPU usage is 100% on a single thread

### ISSUE THREAD

**Issue by manyet1k** [flathub/org.signal.Signal#325]
OS: Pop!_OS 22.04
CPU: Ryzen 9 5900HX 
RAM: 16GB
My fans began to make a pretty loud noise and when I opened `gnome-system-monitor` to check what was going on, I saw that `signal-desktop --enable-crashpad` had a CPU usage of ~6.25% to 6.33%, which is a single thread out of 16 running at full capacity (though a RAM consumption of 23.9 MB, which I think is fair). This is the first time I'm having that bug ~~and Signal is still running~~. How can I get the necessary logs?

**Comment by Altonss** [comment]
Is this issue still hapenning with the latest version?
I think that this is an upstream issue, see here for example : https://github.com/signalapp/Signal-Desktop/issues/5444
So this issue could be closed for now in favor of the upstream one I think :)

**Comment by manyet1k** [comment]
This never happened again since I've opened this issue. You're right, I'm closing the issue
