### ISSUE TITLE
Window resizes to smallest on Wayland

### ISSUE THREAD

**Issue by julianfairfax** [flathub/org.signal.Signal#346]
It seems that when you resize the window on Wayland, that value is reset randomly. I resize the window to be a bit wider, and suddenly I find it has resized itself back to the smallest size again seemingly at random. The smallest vertical height for the window is also larger than what it is when running through XWayland.

Link to log: https://debuglogs.org/desktop/5.58.0/c7e60b9c9e187ea2f59acaaf1623dccf3604d6eb0d480e99c5b7a354cf8fbf6a.gz

**Comment by julianfairfax** [comment]
Using `flatpak override --user --env=SIGNAL_USE_WAYLAND=1 org.signal.Signal` instead of flatpak run org.signal.Signal --enable-features=UseOzonePlatform,WaylandWindowDecorations --ozone-platform=wayland` *might* have fixed this issue. I will leave it open for a few days and will update it if it occurs again.

**Comment by julianfairfax** [comment]
> Using `flatpak override --user --env=SIGNAL_USE_WAYLAND=1 org.signal.Signal` instead of `flatpak run org.signal.Signal --enable-features=UseOzonePlatform,WaylandWindowDecorations --ozone-platform=wayland` _might_ have fixed this issue. I will leave it open for a few days and will update it if it occurs again.

This did not fix the issue, so it will remain open

**Comment by julianfairfax** [comment]
Upstream issue opened as this also occurs with the official Debian package. https://github.com/signalapp/Signal-Desktop/issues/6113

**Comment by Altonss** [comment]
> Upstream issue opened as this also occurs with the official Debian package. [signalapp/Signal-Desktop#6113](https://github.com/signalapp/Signal-Desktop/issues/6113)

Thanks for testing! Then you can maybe close the issue as it's upstream. We can reopen it later if there is a specific flatpak issue, but as of now this one can be closed I think :)
