### ISSUE TITLE
Use update portal for mandatory update notification

### ISSUE THREAD

**Issue by wjt** [flathub/org.signal.Signal#352]
I opened Signal today and got this:

![Screenshot from 2022-09-15 09-23-47](https://user-images.githubusercontent.com/86760/190354258-c7492bc5-7df6-4818-bf58-ef7904556782.png)

As a user of the Flatpak, linking to the website is not useful. Instead the notification should use the [UpdateMonitor](https://flatpak.github.io/xdg-desktop-portal/#gdbus-org.freedesktop.portal.Flatpak.UpdateMonitor) portal to trigger an update.

(I know that this is impossible unless it is either implemented upstream, or the Flatpak is built from source and hence can be patched.)

**Comment by bermeitinger-b** [comment]
> (I know that this is impossible unless it is either implemented upstream, or the Flatpak is built from source and hence can be patched.)
