### ISSUE TITLE
Unread message count in system tray count starts at 1

### ISSUE THREAD

**Issue by kierun** [flathub/org.signal.Signal#353]
![screenshot](https://user-images.githubusercontent.com/3079575/190381366-a43e82a3-bb44-4b59-8fd6-daa86cfd28c3.png)

I (currently) have no new messages anywhere. Yet the badge (unread message) count remains at 1. Closing and starting Signal does not solve the issue ­— neither is rebooting the machine nor updating Signal via flatpak.

Is there a way I can reset it to zero?

**Comment by JulianGro** [comment]
You guys get tray icons? lol

**Comment by kierun** [comment]
Yeah, we do! And I use [awesome](https://awesomewm.org/) which is even more surprising!

Anyway, the problem appears to have resolved itself by itself. ¯\\\_(ツ)\_/¯ The best kind of problems!
