### ISSUE TITLE
[Feature request]: Integrate release notes in flatpak changelogs :)

### ISSUE THREAD

**Issue by Altonss** [flathub/org.signal.Signal#356]

**Comment by bermeitinger-b** [comment]
This is not something that the update checker bot can do. Where are these changelogs shown anyway?

Also, the changelog would always say "Small tweaks, bug fixes, and performance enhancements. Thanks for using Signal!" like in the upstream repo.

**Comment by Altonss** [comment]
> Where are these changelogs shown anyway?

They are shown inside the app for example, at first opening.

> Also, the changelog would always say "Small tweaks, bug fixes, and performance enhancements. Thanks for using Signal!" like in the upstream repo.

Yes most of the time it's not really informative anyway, you're right (but sometimes they announce new features also) :)

**Comment by bermeitinger-b** [comment]
But where would they be shown for flatpak?

**Comment by Altonss** [comment]
> But where would they be shown for flatpak?

They would be shown in Gnome Software for exemple, when downloading an update there is a changelog screen for each software.
