### ISSUE TITLE
Permission to access all user files denied at install, no notice

### ISSUE THREAD

**Issue by firefoxlover** [flathub/org.signal.Signal#365]
This is no problem, maybe users want it. But you need Flatseal or CLI knowledge to change this permission, and find out that this is the cause for the problem.

Drag and drop does not work because of this.

Solution: display a window saying that this may need to be changed or just allow that from beginning on

**Comment by bermeitinger-b** [comment]
During installation, you can see the permissions that are granted (including file access on host).
