### ISSUE TITLE
Signal Desktop fails to start

### ISSUE THREAD

**Issue by prthorsenjr** [flathub/org.signal.Signal#370]
I am running openSUSE Tumbleweed and have been using Signal Desktop without any issues. This morning, when I attempted to open it, it brought up the application window and attempts to connect but fails and never completes. I've tried rebooting, same issue. I uninstalled the application and reinstalled it, same issue.

**Comment by mogoh** [comment]
Could this be this issue: #358 ?

If you try to start it from commandline like this: `flatpak run org.signal.Signal` and get the same error as #358 then it is probably the same issue.

**Comment by prthorsenjr** [comment]
On Thu, 2022-12-08 at 06:27 -0800, Mogoh Viol wrote:

Could this be this issue: #358<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fflathub%2Forg.signal.Signal%2Fissues%2F358&data=05%7C01%7C%7C06db2af031af475c236208dad92858b9%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638061064548916099%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=GNKPsqcJ0B6S3hx7xPdGEVSj9un%2FYVSBok2JSURkHQo%3D&reserved=0> ?

If you try to start it from commandline like this: flatpak run org.signal.Signal and get the same error as #358<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fflathub%2Forg.signal.Signal%2Fissues%2F358&data=05%7C01%7C%7C06db2af031af475c236208dad92858b9%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638061064548916099%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=GNKPsqcJ0B6S3hx7xPdGEVSj9un%2FYVSBok2JSURkHQo%3D&reserved=0> then it is probably the same issue.

—
Reply to this email directly, view it on GitHub<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fflathub%2Forg.signal.Signal%2Fissues%2F370%23issuecomment-1342820546&data=05%7C01%7C%7C06db2af031af475c236208dad92858b9%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638061064548916099%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=W8PvRj2%2BojCI5qFTiX7MSXSge5LDXxQRwyokgEphYNw%3D&reserved=0>, or unsubscribe<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FASI3LWJ5R4J5235SX5VG4PLWMHV5LANCNFSM6AAAAAASYFKQSQ&data=05%7C01%7C%7C06db2af031af475c236208dad92858b9%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638061064548916099%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=G0QKhtXDfE3H0gNLiv7wQZFBC3j3slUoc4xseR4yxDk%3D&reserved=0>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

Thank you for telling me how to run the application from the command line. I will try that the next time I have an issue starting the application normally. And wouldn't you know it, right after I submitted the bug the application started working.

Pete


--

Peter R. Thorsen, Jr.

***@***.******@***.***>

(434) 962-7623

**Comment by sandeepansg** [comment]
May be [this](https://github.com/signalapp/Signal-Desktop/issues/6181#issuecomment-1349689566) will help

**Comment by bermeitinger-b** [comment]
The current version has problems with showing the tray icon (will be fixed in 6.5.x, currently in beta). If you enable the tray icon and tell it to start minimized, it will start but you can't see or start it.
