### ISSUE TITLE
Big return of the mouse problem on wayland hidpi screen

### ISSUE THREAD

**Issue by ghost** [flathub/org.signal.Signal#375]
The mouse is again un-themed and so insanely little on normal operation and insanely big if hover a link on hidpi screen with wayland.

**Comment by MrRinkana** [comment]
I have not double checked by testing downgrading but for me the issue appeared after upgrade to kde plasma 5.27.

**Comment by MrRinkana** [comment]
Can confirm as fixed, however there are some visual glitches when the cursor enters the window or changes (to a hand or such). It is basically one-ish frame where the cursor appears to have a different position and sometimes a different shape.
