### ISSUE TITLE
Unhandled Promise Rejection - Since Latest  6.4.0 Release on 2nd Feb 2023

### ISSUE THREAD

**Issue by gittykrabs** [flathub/org.signal.Signal#377]
I just updated to the latest Signal version on Flathub (SteamOS) and received the attached error. Reinstalled and removing all user data does not resolve. 

Unhandled Promise Rejection

TypeError: `appLocale` is required
    at load ([REDACTED]/app/locale.js:57:11)
    at App.<anonymous> ([REDACTED]/app/main.js:1270:57)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)

![Signal Error](https://user-images.githubusercontent.com/123652879/216313154-68cdbaf8-5dae-4820-88c9-ace54b35b202.png)

**Comment by bermeitinger-b** [comment]
Seems to be an upstream issue: https://github.com/signalapp/Signal-Desktop/issues/6265
