### ISSUE TITLE
Signal Desktop crashes (Fedora 37)

### ISSUE THREAD

**Issue by prthorsenjr** [flathub/org.signal.Signal#381]
This morning the Flatpak application of Signal Desktop was updated and when trying to run it immediately crashes. Gnome shell output is as follows:

flatpak run org.signal.Signal                                                                                                                                                                                            SIGINT 
Debug: Will run signal with the following arguments: 
Debug: Additionally, user gave: 
Set Windows Application User Model ID (AUMID) { appUserModelId: 'org.whispersystems.signal-desktop' }
NODE_ENV production
NODE_CONFIG_DIR /app/Signal/resources/app.asar/config
NODE_CONFIG {}
ALLOW_CONFIG_MUTATIONS undefined
HOSTNAME undefined
NODE_APP_INSTANCE undefined
SUPPRESS_NO_CONFIG_WARNING undefined
SIGNAL_ENABLE_HTTP undefined
userData: /home/prt7u/.var/app/org.signal.Signal/config/Signal
config/get: Successfully read user config file
config/get: Successfully read ephemeral config file
LaunchProcess: failed to execvp:
xdg-settings
LaunchProcess: failed to execvp:
xdg-settings
[2:0207/065618.449574:ERROR:ozone_platform_x11.cc(239)] Missing X server or $DISPLAY
[2:0207/065618.449637:ERROR:env.cc(255)] The platform failed to initialize.  Exiting.

I am running the Gnome Desktop (Wayland) and have not had any issues prior to this update.

**Comment by bermeitinger-b** [comment]
Apparently, falling back to x11 is a bad idea. Will correct that shortly.
