### ISSUE TITLE
Signal fails to display tray icon when started with SIGNAL_START_IN_TRAY=1 env variable

### ISSUE THREAD

**Issue by pkorba** [flathub/org.signal.Signal#389]
After today's update Signal no longer shows tray icon when started with `SIGNAL_START_IN_TRAY=1` environment variable. I can see the application is running in the background, though. With `SIGNAL_START_IN_TRAY=0` it starts with no problems, the app is perfectly usable. If the env variable is set, I can see the following message in command line when the app is started:
`[2:0207/182322.582366:ERROR:bus.cc(562)] Failed to get the ownership of org.kde.StatusNotifierItem-2-1: org.freedesktop.DBus.Error.ServiceUnknown`

### System specifications:
Operating System: Fedora Linux 37
KDE Plasma Version: 5.26.5
KDE Frameworks Version: 5.102.0
Qt Version: 5.15.8
Kernel Version: 6.1.9-200.fc37.x86_64 (64-bit)
Graphics Platform: X11
Signal Version: 6.4.1

**Comment by bermeitinger-b** [comment]
I think you have to wait for the 6.5.x release.

**Comment by bermeitinger-b** [comment]
Can you check this version from #390 ?

The bot tells you how to install.

**Comment by pkorba** [comment]
Yes, this fixes the problem. It seems that enabling `sockets=session-bus` also works as a workaround
