### ISSUE TITLE
Flatseal shows that permission 'Session Bus'  / 'Owns' is 'org.kde.*' and it's not clear why

### ISSUE THREAD

**Issue by lestephane** [flathub/org.signal.Signal#418]
**Talks** permissions are very fine grained, but **Owns** is not, can this be shrunk to fit?

![image](https://user-images.githubusercontent.com/5460884/225254892-d1b0f51e-7e09-4970-b732-562deabf0459.png)

**Comment by bermeitinger-b** [comment]
It's for the tray icon for KDE.

We can't know which id KDE will give the application, so it needs to be able to talk to all.
