### ISSUE TITLE
Why not a Signal.RPM version?

### ISSUE THREAD

**Issue by serial02** [flathub/org.signal.Signal#428]
Hello Signal Team

When will we have a Signal version in .rpm and/or official repository for Linux openSuse TW or Fedora desktop?
We don't always want to use flatpak

Is it possible to create an official repository for .rpm for openSuse or Fedora?

Thanks in advance for your attention

![Captura de tela de 2023-04-03 16-45-52](https://user-images.githubusercontent.com/32621790/229803422-2ab97342-f856-401d-83d5-f44c78057efb.png)

**Comment by Altonss** [comment]
This is not the official Signal repository, you can have a look at the feature request here https://community.signalusers.org/t/signal-desktop-for-non-apt-linux-distributions/1356 .
