### ISSUE TITLE
Signal Beta on Flatpak does not worked 

### ISSUE THREAD

**Issue by dtantono** [flathub/org.signal.Signal#432]
Hi
I know there is an url to search for Signal Beta (https://github.com/flathub/org.signal.Signal/pull/372). But, when I typed it on terminal (Steam Deck ). it does not worked.

![image](https://user-images.githubusercontent.com/29157187/231369467-d95f6271-c98a-497f-a641-e76d553ffab9.png)

**Comment by bermeitinger-b** [comment]
Please read the readme.

```
flatpak remote-add --if-not-exists flathub-beta https://flathub.org/beta-repo/flathub-beta.flatpakrepo
flatpak install flathub-beta org.signal.Signal
```
