### ISSUE TITLE
Installing on Chrouton: Nothing matches org.signal.Signal in remote flathub

### ISSUE THREAD

**Issue by rraggl** [flathub/org.signal.Signal#446]
Trying to install Signal Desktop on my Lenovo Duet 5 Chromebook. Did not succeed with the official instruction to install the .deb package, so I thought I give the flathub version a try. 

However, I do get this error message every time I try, while I can install other flathub packages without issues. Thought you might want to know.

![screenshot-nimbusweb me-2023 05 13-12_07_09](https://github.com/flathub/org.signal.Signal/assets/17989199/6cf7d365-cc57-412a-a84d-d7804a96b30f)

uname -a output: Linux penguin 5.15.95-16525-g33e57601bd30 #1 SMP PREEMPT Fri Apr 14 09:39:36 PDT 2023 aarch64 GNU/Linux

**Comment by bermeitinger-b** [comment]
It's currently (same as upstream) only compatible with x64_86 (see #208)
