### ISSUE TITLE
Window gets progressively larger each time it's quit and reopened

### ISSUE THREAD

**Issue by julianfairfax** [flathub/org.signal.Signal#453]
Since the last update, each time I quit and then reopen Signal (not from the tray), the window gets progressively larger. This continues until it fills my whole screen.

cc https://github.com/flathub/im.riot.Riot/issues/362; this is probably an Electron issue

**Comment by razzeee** [comment]
I've restarted mine just now for four times and I'm not seeing this.

With:
- Gnome
- Wayland
- Nvidia

**Comment by razzeee** [comment]
No, I'm using default permissions and just run it from gnome via gui. So it's using xwayland and your problem seems to be with electron and wayland then I guess?
