### ISSUE TITLE
Window controls missing on Linux

### ISSUE THREAD

**Issue by julianfairfax** [flathub/org.signal.Signal#475]
Since the last update, the window controls are missing on Linux

![Screenshot from 2023-06-29 15-12-39](https://github.com/flathub/org.signal.Signal/assets/43753131/4c051c67-c470-4ff1-9e57-7bb916a4f9e7)

cc https://github.com/flathub/im.riot.Riot/issues/377; this is probably an Electron issue

**Comment by bbhtt** [comment]
Are you running it with SIGNAL_USE_WAYLAND=1?

Electron regression https://github.com/electron/electron/issues/38786

If you remove that I think it'll default to xwayland, which isn't affected.
