### ISSUE TITLE
Wayland mode does not display window buttons.

### ISSUE THREAD

**Issue by RayJW** [flathub/org.signal.Signal#483]
I think this has been an issue for at least 2–3 releases now, but when you enable Wayland mode, you lose the window buttons. You do still get window decorations, proper scaling etc. but no minimize, maximize and close buttons. I currently don't own a Debian based device, so I can't test if this is an upstream issue, but I didn't see any Electron changes lately, so I thought I'd start here.

**Comment by genodeftest** [comment]
I have seen this issue too, at least with Signal 6.26.0. With today's update to Signal 6.27.0, the issue is gone for me. Can you please try updating to the latest release?

**Comment by RayJW** [comment]
I can confirm that the upstream update to 6.27.0 did fix this issue, thanks!
