### ISSUE TITLE
Task Tray Icon Isn't Enabled

### ISSUE THREAD

**Issue by ThisNekoGuy** [flathub/org.signal.Signal#502]
Signal supports using a task tray icon (it keeps the application running when closing the window), but this isn't enabled by the flatpak for some reason.

(Also, know that using the task tray icon option as an argument to the app causes subsequent clicks of the `.desktop` file to open new instances of Signal; this is a bug, but no one upstream seems interested in fixing it for some reason. I've also contacted Signal directly about this before and they just didn't care because we're Linux users. :upside_down_face: )

**Comment by bermeitinger-b** [comment]
It is not enabled by default because the official version does not use it by default.
You can enable it: Read the README.

**Comment by ThisNekoGuy** [comment]
@bermeitinger-b I'm aware, that's explicitly why I'm bringing this up. The fact that this is the default behavior, officially, is stupid; users shouldn't be forced to modify it when this is _**not**_ the default behavior for other platforms.
