### ISSUE TITLE
[Bug] Drag and Drop

### ISSUE THREAD

**Issue by VuzzyM** [flathub/org.signal.Signal#503]
Pictures don't upload, the directory doesn't matter, with only drag and drop not work. Please fix.

![image](https://github.com/flathub/org.signal.Signal/assets/66425682/8a6bd0e9-3d51-4af8-ab61-fa62cba26bd7)

Version signal: 6.29.1

OS: Linux mint xfce 21.1

**Comment by emarleau** [comment]
I'm having the same issue since a long time. Right now I'm using version version 7.9.0 from flathub.
