### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by Victor239** [flathub/org.signal.Signal#520]
Flathub allows changelogs for each new release - can these be automated?

**Comment by bermeitinger-b** [comment]
Surely, but where would it show them? We discussed this in #356 already

We pull the deb package from the servers and would need to realign with the corresponding Github Release.

If you provide a PR, no one is stopping you.

**Comment by Victor239** [comment]
Apologies, didn't see that issue. 

Changelogs are displayed on Flathub and within distro app updaters (e.g. KDE Discover, GNOME Software), all that's needed is an `.appdata`/[.metainfo.xml](https://docs.flatpak.org/en/latest/conventions.html#appdata-files) file. 

See these examples of another app's [appdata.xml](https://github.com/flathub/io.github.trigg.discover_overlay/blob/master/io.github.trigg.discover_overlay.appdata.xml), and how their changelog is [displayed on Flathub](https://flathub.org/en-GB/apps/io.github.trigg.discover_overlay).
