### ISSUE TITLE
Notification not working since the removal of "org.freedesktop.Notifications"

### ISSUE THREAD

**Issue by Luiz-C-Lima** [flathub/org.signal.Signal#556]
With the removal of org.freedesktop.Notifications here #525, I can't get any notifications without adding org.freedesktop.Notifications back to permissions.

Signal Version: 6.39.1
Libnotify Version: 0.8.3
Notification Daemon: Dunst 1.9.2

OS: EndeavourOS
DE/WM: Hyprland 0.30.0-1

**Comment by superuser-miguel** [comment]
I found that it works though Portals, but it is not active. Use Flatseal to activate Portals Notifications

![2024-02-18_15-49-42](https://github.com/flathub/org.signal.Signal/assets/16271056/0cbedb72-8b5a-49e8-b4d9-d17928144cab)
