### ISSUE TITLE
Extremely low PPI

### ISSUE THREAD

**Issue by xplosionmind** [flathub/org.signal.Signal#559]
Possibly related to #333.

As you might infer from the screenshot below, the Signal app installed via Flatpak has a super low PPI level:

![Screenshot from 2023-12-03 16-50-21](https://github.com/flathub/org.signal.Signal/assets/42862428/9fd682b6-cf6b-41e0-b4e0-fcf74155d31e)

If I try to change the settings forcing Wayland use…

![Screenshot from 2023-12-03 16-52-59](https://github.com/flathub/org.signal.Signal/assets/42862428/dde5c06c-84d4-4169-bb3e-595080ff4c26)

… I get the following error:

```
Debug: Will run signal with the following arguments: 
Debug: Additionally, user gave: 
Set Windows Application User Model ID (AUMID) { AUMID: 'org.whispersystems.signal-desktop' }
NODE_ENV production
NODE_CONFIG_DIR /app/Signal/resources/app.asar/config
NODE_CONFIG {}
ALLOW_CONFIG_MUTATIONS undefined
HOSTNAME undefined
NODE_APP_INSTANCE undefined
SUPPRESS_NO_CONFIG_WARNING undefined
SIGNAL_ENABLE_HTTP undefined
userData: /home/tommi/.var/app/org.signal.Signal/config/Signal
config/get: Successfully read user config file
config/get: Successfully read ephemeral config file
LaunchProcess: failed to execvp:
xdg-settings
LaunchProcess: failed to execvp:
xdg-settings
[2:1203/165315.794040:ERROR:ozone_platform_x11.cc(240)] Missing X server or $DISPLAY
[2:1203/165315.794076:ERROR:env.cc(255)] The platform failed to initialize.  Exiting.
The futex facility returned an unexpected error code.
```

**Comment by der-eismann** [comment]
Did you follow the Wayland section in the readme?
https://github.com/flathub/org.signal.Signal#wayland

**Comment by xplosionmind** [comment]
I did, but your comment made me try another time tweaking variables a bit more, and the problem looks solved now. Thanks a lot!
