### ISSUE TITLE
Database error after upgrade -- App crashing while it is starting -- Unhandled Promise Rejection 

### ISSUE THREAD

**Issue by No565** [flathub/org.signal.Signal#563]
After updating i got this error message :

Unhandled Promise Rejection 
Error: Not initializedat MainSQL.close ([REDACTED]/ts/sql/main.js:104:13)at BrowserWindow.<anonymous> ([REDACTED]/app/main.js:710:15)

It asked me if i want to delete everything and after it it will work, but i dont want to do that so i tried to reinstall the package and got the same error... after a while i tried to go as it suggests, deleting everything but it not worked, i think it was undble to complete the deletion... i don´t know... if its possible it would be cool to have my chats and photos as they were, i dont really want to get rid of them ( : ...

It might be related to this :  App crashing while it is starting (sometimes) #560 
and this : I think it is simiar to this one "  Database error after upgrade to 6.30 #6597 " (https://github.com/signalapp/Signal-Desktop/issues/6597)  but not sure.

The signal desktop is on a Linux Mint 21 Cinnamon. I dont know which signal version is that currently because i cannot open the app, but it is the latest flathub version found on the Software Center!

**Comment by bermeitinger-b** [comment]
This looks like your database file is (unrecoverably)  damaged.

Your chats and photos are on your phone.

**Comment by No565** [comment]
How is that possible ? I just updated the program as i always did ( : ...

No because i changed my phone since i have the desktop app, so i have only a partially data from the desktop app on my phone, not everything :/ therefore it would be nice to have access to that files, even if i cannot use signal , like how can i install the previous version ? That run just fine ! Or any way to get the images out of the system, the chat doesnt bothers me if it gets lost but the imgs would be nice to have them all ( : Any idea ? Thx!!!
