### ISSUE TITLE
This version of Signal Desktop has expired.

### ISSUE THREAD

**Issue by ChildishGiant** [flathub/org.signal.Signal#568]
I have a message saying I need to update, despite being up to date with this package.

![image](https://github.com/flathub/org.signal.Signal/assets/13716824/fe1fd3d1-77fb-4dd5-a9ab-437af478b8f3)
"This version of Signal Desktop has expired. Please upgrade to the latest version to continue messaging. Click to go to signal.org/download"

**Comment by ChildishGiant** [comment]
When trying to send a message I get an error too
![image](https://github.com/flathub/org.signal.Signal/assets/13716824/9e25717e-a776-4952-95d6-19f4feefc784)

**Comment by bermeitinger-b** [comment]
The latest release is what is deployed:
```
Signal Desktop	Private messenger	org.signal.Signal	6.43.0-beta.3	beta	flathub-beta
Signal Desktop	Private messenger	org.signal.Signal	6.42.0	stable	flathub
```

And I can't replicate. Did you restart Signal after updating?

What does `flatpak info org.signal.Signal` give you?

**Comment by ChildishGiant** [comment]
I can't remember when but in the end I couldn't get my flatpak to update and I just had to reinstall, losing all my messages :( I think it was some odd issue with my flatpak install, not this app.
