### ISSUE TITLE
The application keeps freezing

### ISSUE THREAD

**Issue by aleixpol** [flathub/org.signal.Signal#57]
I can't use it for more than few seconds since the last update.

**Comment by bermeitinger-b** [comment]
I think you need to wait until the messages are converted to another DB scheme. It took a few minutes for me.

**Comment by aleixpol** [comment]
I tried again, for about 1h and nothing changed. No, no error messages on the UI. I could try running it from the command line, if that helps.

**Comment by bermeitinger-b** [comment]
I can't reproduce your issue, it is working fine. Please attach the output of the command line if you run it from there `flatpak run org.signal.Signal`

**Comment by aleixpol** [comment]
`{"name":"log","hostname":"seu","pid":3,"level":30,"msg":"SQL channel job 262 (searchConversations) succeeded in 15ms","time":"2018-11-21T15:40:29.059Z","v":0}`

This is the last line I saw before freezing.

**Comment by bermeitinger-b** [comment]
Do you have many messages? You could try removing the data folder and start anew. I know this may not be satisfactory but at least you'll have a working version.

**Comment by aleixpol** [comment]
Doesn't happen since recently.
