### ISSUE TITLE
fcitx5 not working in Signal Desktop flatpak

### ISSUE THREAD

**Issue by codewiz** [flathub/org.signal.Signal#577]
I use fcitx5 + mozc for Japanese input. Works fine in both Qt and GTK apps, including flatpak GTK apps such as com.github.tchx84.Flatseal, which is GTK4.

This is within a KDE Plasma Wayland session.

**Comment by czhang03** [comment]
Electron app do not support IME on wayland session because of a upstream chrome bug. see https://github.com/flathub/org.signal.Signal/issues/580 , https://bugs.chromium.org/p/chromium/issues/detail?id=1039161 , https://github.com/electron/electron/issues/33662

**Comment by codewiz** [comment]
> I think the wayland as default change is getting reverted #582 . I personally like wayland by default, but I would like an option (like an environment variable) to revert it.

Updating the flatpak today picked up the revert, and I can confirm that now signal-desktop runs as an XWayland client, which fixes the bug for me.

**Comment by codewiz** [comment]
> Electron app do not support IME on wayland session because of a upstream chrome bug. see #580 , https://bugs.chromium.org/p/chromium/issues/detail?id=1039161 , [electron/electron#33662](https://github.com/electron/electron/issues/33662)

fcitx5 + mozc works for me in Chrome 120.0.6099.199 within a Plasma Wayland session, but I run it with these arguments:

```
--enable-features=WebUIDarkMode --force-dark-mode --force-device-scale-factor=1.0 --ozone-platform-hint=auto --gtk-version=4
```
