### ISSUE TITLE
Signal Flatpak enabled ozone-platform-hint=auto by default, please consider to reverse it

### ISSUE THREAD

**Issue by sith-on-mars** [flathub/org.signal.Signal#580]
Hi I just noticed that Signal Flatpak enabled `ozone-platform-hint=auto` by default since the last update.

![image](https://github.com/flathub/org.signal.Signal/assets/37974764/8684792d-80ce-461e-9578-dec7c67a410d)

I'm not sure it's a very good idea for now, since Electron upstream hasn't enabled this option by default due to numerous Wayland related bugs. ASFSIK all of the other Electron apps I use don't enable this option by default. Perhaps it would be better to enable  `ozone-platform-hint=auto` when the upstream enables it.

**Comment by bermeitinger-b** [comment]
Do you actually have issues with this change or do you think it will lead to problems later on?

**Comment by sith-on-mars** [comment]
Yes I do. For example, input methods don't work and the app looks blurry in my HiDPI display. Electron apps still have a long way to go to be Wayland friendly.

**Comment by czhang03** [comment]
Hi, I personally have no problem for wayland by default, but I think we need an option to turn it off. 
Input method is essential for me on Signal, as I do need to use a CJK language in Signal, which is impossible without input method. But I know it is not a common requirement. It seems like Electron app has a long way to go to support IME as chrome team is very dismissive of text-input-v3 (probably for valid reason, but bad support is better than no support) https://bugs.chromium.org/p/chromium/issues/detail?id=1039161

Electron app seems to be pretty crisp on wayland for both of my computers, so I don't encounter a problem on that regard. In fact, wayland app is much more crisp than xwayland app especially with fractional scaling.

So, my question is, is there a way for me to turn wayland off or do I need to wait for an update?
