### ISSUE TITLE
Fails to start after update to 6.45.0

### ISSUE THREAD

**Issue by hadess** [flathub/org.signal.Signal#597]
```
Jan 25 11:07:24 classic org.signal.Signal.desktop[308969]: userData: /home/hadess/.var/app/org.signal.Signal/config/Signal
Jan 25 11:07:24 classic org.signal.Signal.desktop[308969]: config/get: Successfully read user config file
Jan 25 11:07:24 classic org.signal.Signal.desktop[308969]: config/get: Successfully read ephemeral config file
Jan 25 11:07:25 classic org.signal.Signal.desktop[309018]: LaunchProcess: failed to execvp:
Jan 25 11:07:25 classic org.signal.Signal.desktop[309018]: xdg-settings
Jan 25 11:07:25 classic org.signal.Signal.desktop[309021]: LaunchProcess: failed to execvp:
Jan 25 11:07:25 classic org.signal.Signal.desktop[309021]: xdg-settings
```

```
Signal Desktop - Private messenger

          ID: org.signal.Signal
         Ref: app/org.signal.Signal/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 6.45.0
     License: AGPL-3.0-only
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 437.3 MB
     Runtime: org.freedesktop.Platform/x86_64/23.08
         Sdk: org.freedesktop.Sdk/x86_64/23.08

      Commit: 5c4d7812c325c7c4e05a4adc10082893d240aa21a39b623549b6fff35292ee5f
      Parent: 2751a68d673123eed2cb17670cdc69d35b6fa37c38323bf150a57660ce5c2667
     Subject: Update signal-desktop.deb to 6.45.0 (1660024d)
        Date: 2024-01-24 22:58:15 +0000
```

Looks like https://github.com/flathub/org.signal.Signal/pull/595 got merged without human intervention, and introduced this regression. The easier fix would be to revert the patch. Ideally, a replacement for `xdg-settings` that can provide signal with the information it needs would be implemented and we could use `6.45.0`.

**Comment by hadess** [comment]
This is probably due to changes in Electron. This is the code that uses `xdg-settings`:
https://github.com/electron/electron/blob/921da723b8707d7438da1d39534e4d4d50a6f5ea/shell/browser/browser_linux.cc#L26

**Comment by hadess** [comment]
Looks like we need a version of `xdg-settings` that can confirm that we are the default handlers for the 2 URI schemes mentioned in the `.desktop` file:
```
MimeType=x-scheme-handler/sgnl;x-scheme-handler/signalcaptcha;
```

**Comment by bermeitinger-b** [comment]
Your terminal output is not complete. And are you using wayland?

**Comment by hadess** [comment]
> Your terminal output is not complete. And are you using wayland?

It's not complete because I didn't think anything else was needed, it just bailed after that. Yes, I use Wayland (but it uses XWayland anyway, right?).

But it seems that it works now. Let's just attribute this to me not being awake...
