### ISSUE TITLE
Notifications not removed

### ISSUE THREAD

**Issue by bermeitinger-b** [flathub/org.signal.Signal#6]
I'm using Cinnamon with Fedora 27 and this flatpak package in its version 1.0.40.
Every time I'm receiving a new message, my desktop environment (Cinnamon 3.6.6) shows the notification and increases the notification counter in the tray by one.
So far, so good. Unfortunately, with this package, the notification counter is not decreased once I read the messages. I have to manually click the notification symbol and clear all notifications.

![notifications](https://user-images.githubusercontent.com/581257/33662806-855084cc-da8d-11e7-8670-596da38e77a6.png)

The screenshot shows two incoming messages. After reading them, the notifications still are shown.

Outside flatpak, so building the project manually with yarn, I don't have that problem and it is synced once I read a message.
I don't understand flatpak to that detail, such that I could modify it on my own.

**Comment by TingPing** [comment]
There is nothing special about notifications in flatpak, we grant it full access to do its thing.

**Comment by bermeitinger-b** [comment]
Be that as it may, but still there is room to investigate. The problem does not happen with a manual build of the same version. (Now at 1.0.41)
