### ISSUE TITLE
flathub verification?

### ISSUE THREAD

**Issue by qoijjj** [flathub/org.signal.Signal#600]
Getting verification would allow an increased level of user trust.

https://discourse.flathub.org/t/how-do-you-get-a-flathub-submission-verified/3714
https://flathub.org/apps/collection/verified/1

I believe this would require the blessing of upstream devs via hosting a file.

**Comment by qoijjj** [comment]
> This is an unofficial repackaging. None of the maintainers have access to signal.org to add the verification file.

Right but if you're open to it, it could be requested of upstream.

> Who do you want to be verified anyway?

I don't understand the question

**Comment by storopoli** [comment]
I use [`secureblue`](https://github.com/secureblue/secureblue) and one of the hardenings that it applies is to only allow flatpaks from `flathub-verified`.
It is quite outrageous that a non-official Signal client is verified, e.g. [Flare](https://flathub.org/apps/de.schmidhuberj.Flare), and Signal Desktop is not.

**Comment by bermeitinger-b** [comment]
The official developers don't care about flatpak. 🤷

(Time-wise, I'm not judging.)

You could buy the domain signal-flatpak.org, verify it, and add it here.

**Comment by qoijjj** [comment]
@storopoli please see [this](https://github.com/secureblue/secureblue/issues/193#issuecomment-1953323680), [this](https://github.com/secureblue/secureblue/issues/193#issuecomment-1955443449), and most importantly [this](https://github.com/secureblue/secureblue/issues/171#issuecomment-1922616322). Please do not reference secureblue in upstream reports especially for tickets like this which aren't even scenarios recommended by secureblue, as it reflects badly on the project.

Upstream devs aren't interested in verification, so this ticket should be closed and possibly locked at this point.
