### ISSUE TITLE
Please get verified on Flathub

### ISSUE THREAD

**Issue by TriVoxel** [flathub/org.signal.Signal#619]
Flathub is by far the de facto way for most average Linux users/new Linux users to install applications. I noticed that the "[Signal Desktop](https://flathub.org/apps/org.signal.Signal)" does not have a "verified" status on the developer name. This signals to the user that the app may not be coming from an official or trustworthy source.

I believe this is either because the Flatpak app for Signal is packaged by the community, or the verification process had an oversight. Please get your developer profile verified, and/or take ownership and responsibility for the packaging of the  app on Flathub so that users can better trust the integrity of the software. Flatpak builds can be automatically packaged and published to Flathub using CI.

**Comment by bermeitinger-b** [comment]
Please look here https://github.com/flathub/org.signal.Signal/issues/600
