### ISSUE TITLE
Please compile for ARM64 on Linux

### ISSUE THREAD

**Issue by TriVoxel** [flathub/org.signal.Signal#620]
Please compile and distribute an ARM64 binary for Linux, as ARM64 is becoming a more popular architecture every day, and there are many ARM64 users. Please publish an ARM64 build on Flathub, too.

**Comment by bermeitinger-b** [comment]
We don't even compile the x86 version.
Once there is an official arm version, we'll check again.

**Comment by bermeitinger-b** [comment]
See here https://github.com/flathub/org.signal.Signal/issues/137 and https://github.com/flathub/org.signal.Signal/issues/208
