### ISSUE TITLE
Unable to instal Signal Desktop app

### ISSUE THREAD

**Issue by lubo99** [flathub/org.signal.Signal#623]
i am bit of frustrated now... archlinux on android 14 flatpak wont install signal app

**Comment by bermeitinger-b** [comment]
🤫

**Comment by lubo99** [comment]
[root@localhost refs]# flatpak install -u --arch=ARCH org.signal.Signal
Looking for matches…
error: No remote refs found for ‘org.signal.Signal’

[root@localhost refs]# flatpak --version
Flatpak 1.15.6

[root@localhost refs]# flatpak list && flatpak remotes
Name    Options
flathub system
flathub user


archlinux runing in android tablet

**Comment by lubo99** [comment]
> 🤫

please see my note below. unable to install signal using flatpak... I am pretty mad ... archlinux sucks to be honest. can't get signal desktop working...

**Comment by lubo99** [comment]
so for arm what do you advise? i am sure that pretty almost every tablet and smartphone these days runs on arm. there must be solution.
