### ISSUE TITLE
Freedesktop complications

### ISSUE THREAD

**Issue by LanceHaverkamp** [flathub/org.signal.Signal#64]
While the Flatpak version works, there is a **huge** FreeDeskop dependency,  Is there a way around this?  I've seen this in KDE version from both Ubuntu & Fedora.

**Comment by bermeitinger-b** [comment]
From my understanding, the base image (electron) also relies on FreeDesktop, so it wouldn't matter if Signal uses another runtime.

**Comment by TingPing** [comment]
Well it can't run on magic. Flatpak works by having runtimes; Sure they are somewhat large but they are shared between apps.
