### ISSUE TITLE
Pinging Google servers

### ISSUE THREAD

**Issue by bmp** [flathub/org.signal.Signal#668]
Why does the flatpak ping Google servers? The following IPs are touched:

1. 142.250.196.83
2. 142.250.71.42

You can check this after launching the Signal flatpak and then running https://github.com/berthubert/googerteller to check.

**Comment by bermeitinger-b** [comment]
Signal is hosted on Google Cloud.

https://www.nslookup.io/domains/storage.signal.org/dns-records/
