### ISSUE TITLE
SIGNAL_USE_TRAY_ICON=1 not working anymore

### ISSUE THREAD

**Issue by cassepipe** [flathub/org.signal.Signal#686]
I added SIGNAL_USE_TRAY_ICON=1 to flathub Signal thanks to flatseal. 

It used to work but it does not anymore with a recent update. Is it still supposed to work ?

I am running Fedora 40 Cinnamon spin.

**Comment by bermeitinger-b** [comment]
It's now available directly in the settings. You don't need the additional var.

![Screenshot_20240706_163019](https://github.com/flathub/org.signal.Signal/assets/581257/5d7925cf-6b9c-4e9e-beb2-3340ed5b7a9c)

**Comment by cassepipe** [comment]
I did not expect that. Thanks !
