### ISSUE TITLE
Tray icon no longer present after recent Signal upgrade/s

### ISSUE THREAD

**Issue by r2rX** [flathub/org.signal.Signal#690]
Hello all,

I'm a tad delayed posting this but after an upgrade a few versions back, the tray icon is no longer present/displayed. I've confirmed that SIGNAL_USE_TRAY_ICON=1 is still active in the environmental variables (via Flatseal). If there's any further info/testing required, I'm happy to provide. Cheers.

Operating System: Fedora Linux 40
KDE Plasma Version: 6.1.3
KDE Frameworks Version: 6.4.0
Qt Version: 6.7.2
Kernel Version: 6.9.9-200.fc40.x86_64 (64-bit)
Graphics Platform: Wayland
Processors: 16 × AMD Ryzen 9 5900HX with Radeon Graphics
Memory: 30.7 GiB of RAM
Graphics Processor: AMD Radeon RX 6800M

**Comment by bermeitinger-b** [comment]
There are settings in the main application to control the tray icon. The environment variables are no longer in effect.
