### ISSUE TITLE
Keyring does not seem to be used 

### ISSUE THREAD

**Issue by lucasmz-dev** [flathub/org.signal.Signal#691]
Not sure if a strong indicator or anything, but usually other apps like Element, Chromium based stuff, Bitwarden, show entries in GNOME's Passwords and Keys app. I see nothing about Signal despite the recent changes. Suspecting it may be a flatpak version issue.

**Comment by lucasmz-dev** [comment]
Nevermind. I think it didn't land in 7.16.0 yet. If I see this issue on 7.17.0 I'll reopen.

**Comment by lucasmz-dev** [comment]
Seems like this is an issue with 7.17.

**Comment by lucasmz-dev** [comment]
I tried also adding the org.freedesktop.Secrets permission that other apps use in Flatseal to see if it helps but it doesn't seem like it?

**Comment by lucasmz-dev** [comment]
Oh. I'm on Mint 22 now, and giving permission to org.freedesktop.secrets works. That's interesting.

**Comment by saibotk** [comment]
Also tested this on Gnome, and it works the first time, but then somehow crashes the gnome keyring deamon.
And when restarting signal it will always just show an error about the database being corrupted, but changing the config back to the legacy key will restore access...
Seems like something might be wrong on Signal's side here?

**Comment by lucasmz-dev** [comment]
I didn't specify before, but when not even giving permission helped, I was in Fedora 40 (more specifically Ultramarine 40)

**Comment by teynav** [comment]
Same happens on Opensuse, Keyring crashes and signal-desktop can't never be opened back (using GNOME 46)

**Comment by akvadrako** [comment]
more info: https://github.com/flathub/org.signal.Signal/issues/694

**Comment by lucasmz-dev** [comment]
I don't think it that issue is the same as the one here @teynav @saibotk @akvadrako, this was about the missing permission for org.freedesktop.Secrets, for me, it seems to actually work now just fine in Fedora when it is given. I think you guys should file another / follow #694.

**Comment by akvadrako** [comment]
But this permission isn't given, is it? Why do you think there is another problem besides the lack of this permission?

**Comment by lucasmz-dev** [comment]
I'm still lost exactly on what's broken, I just know previously on Fedora GNOME just giving the permission didn't work
AFAIK Signal works without access to the keyring usually, just with the key exposed, the issues mentioned kind of sound like it was previously used and then access was lost since wasn't really what I mentioned here originally
