### ISSUE TITLE
flathub page states misleading developer

### ISSUE THREAD

**Issue by AtFreezingPoint** [flathub/org.signal.Signal#722]
Hello, I believe that even though the unverified tag is there the developer/publisher should not be stated as that part in the website is generally used for developers & publishers of the apps; including some official afaik even though they've not verified it.
![image](https://github.com/user-attachments/assets/27296c6b-81a3-47b8-b561-1a14deaba950)

**Comment by bermeitinger-b** [comment]
The application is still developed by the Signal Foundation.

**Comment by AtFreezingPoint** [comment]
> The application is still developed by the Signal Foundation.

But it is packed by not the signal foundation

**Comment by sukahiroaki** [comment]
This is how it is on Flathub in general, nothing Signal specific. So this bug should be closed, the Signal Flatpak maintainers are doing everything right in this respect.

**Comment by axelsimon** [comment]
I agree there's an issue here, https://flathub.org/apps/org.signal.Signal looks like it's the official Signal Foundation Flatpak packaging of Signal Desktop.

If it's not, and it's a community packaging of Signal Desktop, it needs to be made clear.

Otherwise it's like thinking Debian's packaging of MariaDB is done by the MariaDB folks and not by Debian Developers.

**Comment by axelsimon** [comment]
> The application is still developed by the Signal Foundation.

If they are not the ones making this specific Flatpak available, their name shouldn't be on it.

**Comment by shibacomputer** [comment]
From a UX perspective, this is ambiguous. Someone who is generally familiar with computers and Software stores but _not_ familiar with the workings of Flatpak is likely to interpret this as wholly published by the Signal team, _and_ that this fact is unverified by the software store.

This kind of ambiguity is the opposite of the purpose of code trust, and the labelling should be more explicit. The UX should treat developers and packagers similar to platforms that delineate developer from publisher (for example, Steam.)

For example:

**Signal Desktop**
Developed by Signal Foundation
Packaged by [name] with a tooltip or similar element that provides additional context.

**Comment by shibacomputer** [comment]
Definitely this is the wrong place for my comment, sorry for the off-topic post!

**Comment by bermeitinger-b** [comment]
This is the typical approach that Flathub accepts. Please contact either Flathub, if you want this feature (_repackaged_) or Signal, if you want them to claim this Flathub package and make if official. (the latter will no happen in the near future)

**Comment by AtFreezingPoint** [comment]
> This is the typical approach that Flathub accepts. Please contact either Flathub, if you want this feature (_repackaged_) or Signal, if you want them to claim this Flathub package and make if official. (the latter will no happen in the near future)

Is this not flathub?

**Comment by bermeitinger-b** [comment]
This is an instance of a community repo. The problem you're describing counts for all of Flathub and is not specific to Signal.
