### ISSUE TITLE
Confusing dialog when starting and keytring database error

### ISSUE THREAD

**Issue by pabl0** [flathub/org.signal.Signal#746]
In recent change related to storage provider selection env variables, a warning dialog was added.

However, at least in a Debian 12 system this dialog does not have any meaningful text:
![signal-dialog](https://github.com/user-attachments/assets/c59a6ec2-3fc6-4440-8d73-031869d90876)

Not sure why this is, the running zenity process seems to have the correct parameters:
`zenity --question --no-wrap --default-cancel --icon-name=dialog-warning --title Warning --text Signal is being launched with the <b>plaintext password store</b> by default due to database corruption bugs when using the encrypted backends. This will leave your keys <b>unencrypted</b> on disk as it did in all previous versions.  If you wish to experiment with the encrypted backend, set the environment variable <tt>SIGNAL_PASSWORD_STORE</tt> to <tt>gnome_libsecret</tt>, <tt>kwallet</tt>, <tt>kwallet5 or <tt>kwallet6</tt> depending on your desktop environment using Flatseal or the following command:  <tt>flatpak override --env=SIGNAL_PASSWORD_STORE=gnome-libsecret org.signal.Signal</tt>  Note that the encrypted backends are <b>experimental</b> and may cause data loss on some systems.  Press <b>Yes</b> to proceed with <b>plaintext password store</b> or <b>No</b> to <b>exit</b>.`

Perhaps the zenity program provided by the runtime has some issues?

After answering "Yes" to the question (what else to do without any context?), the following error happens:
![signal-db-error](https://github.com/user-attachments/assets/f9955bcc-5fa1-43fa-8884-eedc862519e6)

**Comment by bermeitinger-b** [comment]
Update again. The build bots are too slow to keep up with the pushes

**Comment by pabl0** [comment]
I guess the faulty dialog got fixed, but I still get the database error if I start Signal the normal way.
Trying to run it with the command line flag

`flatpak run org.signal.Signal --password-store="gnome-libsecret"`

gives the following somewhat scary error:
![signal-db-error2](https://github.com/user-attachments/assets/c6733978-32a0-4d35-bcf4-8d844566310b)

**Comment by pabl0** [comment]
Oopsie daisy, missed that. Restored config.json from yesterday's backup and now Signal starts fine again. Thanks!
