### ISSUE TITLE
Use secrets portal instead of accessing all secrets?

### ISSUE THREAD

**Issue by Altonss** [flathub/org.signal.Signal#757]
There seems to be a flatpak portal enabling access to only application specific secrets. I don't know how well it works, but it would be a great sandboxing/security improvement. See https://docs.flatpak.org/fr/latest/portal-api-reference.html#gdbus-org.freedesktop.portal.Secret .
Edit: it seems migration to the secrets portal might not be that easy, for users that were already storing their keys in the keyring https://github.com/flatpak/xdg-desktop-portal/issues/483 .

**Comment by bbhtt** [comment]
This is a feature request to Electron or Chromium, not here. Unless they support it signal cannot use it.
