### ISSUE TITLE
Signal uses GTK filepicker on KDE Plasma

### ISSUE THREAD

**Issue by eylenburg** [flathub/org.signal.Signal#797]
For downloading and uploading files, it always uses the (horrible) GTK filepicker. If I'm not mistaken, a Flatpak app should always use the native filepicker, right? This only occurred recently, I remember it being the KDE filepicker until maybe a few weeks ago.

**Comment by bermeitinger-b** [comment]
Electron is at fault because they updated their required version of the portals (e.g. the file picker) over eagerly to a version which is not available yet.
There is no other way at the moment than this.

**Comment by bermeitinger-b** [comment]
See https://github.com/electron/electron/issues/43819#issuecomment-2383104130
