### ISSUE TITLE
Blurry tray icon after update 7.36.1

### ISSUE THREAD

**Issue by konomikitten** [flathub/org.signal.Signal#801]
After the most recent update (7.36.1) the tray icon is blurry.

![image](https://github.com/user-attachments/assets/e38dac1a-e709-47db-a6c0-419222712f09)

**Comment by bermeitinger-b** [comment]
We don't do anything special with the tray icon. This issue is somewhat discussed upstream: https://github.com/signalapp/Signal-Desktop/issues/7082
