### ISSUE TITLE
Badge count broken on elementary OS

### ISSUE THREAD

**Issue by peteruithoven** [flathub/org.signal.Signal#85]
I've worked together with Signal to enable badge counts on linux distro's like elementary OS and Ubuntu. Since v1.25.2, when you install Signal from `https://updates.signal.org/desktop/apt`, you'll see something like this when you've got unread messages:
![signal badge count elementary os](https://user-images.githubusercontent.com/523210/60547044-ffefdc00-9d1e-11e9-8a5b-1a8f7ad893ca.png)
![signal badge count ubuntu](https://user-images.githubusercontent.com/523210/60547045-00887280-9d1f-11e9-9208-b2c3e1056491.png)
More info:
https://github.com/signalapp/Signal-Desktop/issues/3387
https://github.com/signalapp/Signal-Desktop/pull/3390

This however doesn't function when Signal is installed through flatpak. 

I'm afraid it's because the desktop name, which is critical for this to work, seems to be renamed: 
https://github.com/flathub/org.signal.Signal/blob/master/org.signal.Signal.json#L10

**Comment by TingPing** [comment]
Perhaps you can convince upstream to rename as-per current desktop-file-spec recommendations. Otherwise the places it references the old name just have to be patched.

**Comment by peteruithoven** [comment]
Alright, but recommendation or not, why actively rename it?

**Comment by TingPing** [comment]
In Flatpak all exported files *must* match the app-id. This prevents conflicts and simplifies the security model where everything is clearly associated with an app.
