### ISSUE TITLE
Update Needed

### ISSUE THREAD

**Issue by 0TWAIN0** [flathub/org.signal.Signal#86]
The current Signal version is outdated. When opening the program, I get a warning, that exchanging messages is not possible any more without update.

**Comment by bermeitinger-b** [comment]
The upstream's repo (https://github.com/signalapp/Signal-Desktop/releases) shows that 1.25.3 is the latest release. Are you sure you're using this version?

**Comment by 0TWAIN0** [comment]
Ah thank you for the hint. It seams my update manager somehow does not install the current update. so my fault.
