### ISSUE TITLE
Can't run Signal anymore: X11 failure

### ISSUE THREAD

**Issue by androclus** [flathub/org.signal.Signal#90]
Hi, I am grateful for this project -- thank you. Signal Desktop via the flatpak has been working great for months now.

But last night I updated a bunch of packages on my OpenSUSE Tumbleweed box, and now I cannot run Signal (yes, I am updated to latest flatpak version of it).  This is what I get:
```
$ flatpak run org.signal.Signal
Gtk-Message: 12:19:24.592: Failed to load module "unity-gtk-module"
Gtk-Message: 12:19:24.592: Failed to load module "canberra-gtk-module"
Invalid MIT-MAGIC-COOKIE-1 key
(signal-desktop:2): Gtk-WARNING **: 12:19:24.592: cannot open display: :99.0
$ _
```
And the above shows the following in a "journalctl -xe" log query:
```
Sep 02 12:39:37 tonka polkitd[1264]: Registered Authentication Agent for unix-process:32378:4889470 (system bus name :1.24556 [flatpak run org.signal.Sig>
Sep 02 12:39:37 tonka systemd[2950]: Started flatpak-org.signal.Signal-32378.scope.
-- Subject: A start job for unit UNIT has finished successfully
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- A start job for unit UNIT has finished successfully.
-- 
-- The job identifier is 94.
Sep 02 12:39:37 tonka polkitd[1264]: Unregistered Authentication Agent for unix-process:32378:4889470 (system bus name :1.24556, object path /org/freedes>
Sep 02 12:39:37 tonka systemd[2950]: flatpak-org.signal.Signal-32378.scope: Succeeded.
-- Subject: Unit succeeded
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- The unit UNIT has successfully entered the 'dead' state.
```

Anything I am doing wrong?

Thanks,
JS

**Comment by TingPing** [comment]
This has nothing to do with Signal and is a more generic Flatpak + X11 issue.

I imagine simply restarting your session will make it go away.

**Comment by androclus** [comment]
Ugh, Indeed, it did. (I had updated 2700+ packages but like an idiot, had not rebooted.)

BTW, the GTK+ error messages are still there, but now Signal gets beyond them and fully starts up, as before. So I guess they can be ignored (if anyone else sees this issue later), as they are not crucial.

Thanks, TingPing.
JS
