### ISSUE TITLE
Signal Desktop freezes Xorg when using mesa 19.2.1 and kernel 5.3.5

### ISSUE THREAD

**Issue by fuzzysloth** [flathub/org.signal.Signal#99]
Original ticket:
https://bugs.archlinux.org/task/64000

Today I've also found a suggestion to upgrade BaseApp to 19.08:
https://discussion.fedoraproject.org/t/some-flatpaks-kill-the-machine-on-f31sb-beta-testing/7673/4

I tried to do this myself today by changing both base-version and runtime-version to 19.08 in org.signal.Signal.json in order to test it, but build fails on libdbusmenu-1:

```
========================================================================
Building module libdbusmenu in /home/stas/packages/org.signal.Signal/.flatpak-builder/build/libdbusmenu-1
========================================================================
...
./configure: line 3080: intltool-update: command not found
checking for intltool >= 0.35.0...  found
configure: error: Your intltool is too old.  You need intltool 0.35.0 or later.
Error: module libdbusmenu: Child process exited with code 1
```
Which is weird because I have intltool 0.51.0-4 on my system (Arch Linux).

The build succeeds without any modifications b.t.w.

**Comment by fuzzysloth** [comment]
Today I've build and tested AUR package: https://aur.archlinux.org/packages/signal
It's working fine - no freezes or any other issues were discovered.

**Comment by TingPing** [comment]
> Which is weird because I have intltool 0.51.0-4 on my system (Arch Linux).

Well this isn't an Arch package..

```sh
cd shared-modules
git pull origin master
```

Will fix it.

**Comment by TingPing** [comment]
Anyway this wouldn't be a package specific issue. Its either a runtime specific issue or generic flatpak one.

**Comment by fuzzysloth** [comment]
Thank you for the tip for shared-modules!
Now I tested and can confirm that upgrading base-version and runtime-version to 19.08, pulling the latest shared-modules and building the application fixes the issue: Signal Desktop stops freezing.

Can you please upgrade runtime dependency and make the new build available on flathub.org?

**Comment by TingPing** [comment]
Interesting.

Well you already did the work and testing so submit a PR =)

**Comment by fuzzysloth** [comment]
Just tested again:

    killall compton
    flatpak -v --user install org.signal.Signal
    gtk-launch org.signal.Signal

Result: Xorg freezes, switching to another workspace, takes 2+ minutes to switch, open console, `killall signal-desktop` to kill it.

    flatpak -v --user uninstall org.signal.Signal
    flatpak install --user https://dl.flathub.org/build-repo/9526/org.signal.Signal.flatpakref
    gtk-launch org.signal.Signal

Result: Signal window shows up, no Xorg freezes.

**Comment by Erick555** [comment]
@TingPing this is known issue: https://gitlab.com/freedesktop-sdk/freedesktop-sdk/issues/893 For now the only workaround is to use feedesktop 19.08 are gnome/kde equivalent.

**Comment by fuzzysloth** [comment]
New release is available on flathub.org but the Platform and SDK dependencies are still old (and still freezes Xorg):
```
% flatpak info org.signal.Signal 

Signal - Private messenger for the desktop

          ID: org.signal.Signal
         Ref: app/org.signal.Signal/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 1.28.0
     License: GPL-3.0
      Origin: flathub
  Collection: org.flathub.Stable
Installation: user
   Installed: 291.8 MB
     Runtime: org.freedesktop.Platform/x86_64/18.08
         Sdk: org.freedesktop.Sdk/x86_64/18.08

      Commit: dedc7d47ab982c5b2de74c4c658eb6e20a5588e5f0813bd494fea609737facf9
      Parent: 3af7749c41db4df8b0b51bc33f1aea31717c55f653917a44c8f8095dd5ee5ec1
     Subject: Update to v1.28.0 (#102) (b51bf8d2)
        Date: 2019-11-14 15:03:22 +0000
```

Is there any particular reason for that?

**Comment by Erick555** [comment]
This was done in https://github.com/flathub/org.signal.Signal/commit/2ee19529a8e9949948df49cb8e8089e22ef4c6bf

**Comment by bermeitinger-b** [comment]
I could not reproduce this issue.

Nevertheless, I have update the BaseApp and Runtime to 19.08 also also the submodule to the latest master commit. (#103 )
